/**
 * Runtime access to translated slot labels for all layouts.
 * Slot labels are extracted from :slot() pseudo-elements in layout CSS
 * and managed through the i18n translation cache.
 */

/**
 * Slot labels mapped by layout and slot name.
 * Schema: \{ [layoutName]: \{ [slotName]: label \} \}
 */
export interface SlotLabelsMap {
  [layoutName: string]: Record<string, string>;
}

/**
 * Default English slot labels (auto-generated from CSS extraction).
 */
const DEFAULT_ENGLISH_LABELS: SlotLabelsMap = {
  callout: {
    message: "Alert message",
  },
  hero: {
    title: "Page title",
    subtitle: "Page description",
  },
  "page-layout": {},
  "rubric-note": {},
  testimonial: {},
  "two-column": {},
  wrapper: {},
};

/**
 * Placeholder for locale-specific labels that would be loaded from i18n cache.
 * In a full implementation, these would be generated by build scripts
 * that read from the translation cache and populate JSON files per locale.
 */
const LOCALE_LABELS: Record<string, SlotLabelsMap> = {
  en: DEFAULT_ENGLISH_LABELS,
  // hu: { ...Hungarian translations... },
  // Other locales loaded at build time
};

/**
 * Get slot labels for a specific locale.
 * Returns both layout-specific labels and English fallbacks.
 *
 * @param locale - BCP47 locale tag (e.g., "hu", "en", "es")
 * @returns Map of slot labels by layout and slot name
 */
export function slotLabels(locale: string = "en"): SlotLabelsMap {
  // Use locale-specific labels if available, fallback to English
  if (LOCALE_LABELS[locale]) {
    return mergeWithFallback(LOCALE_LABELS[locale], DEFAULT_ENGLISH_LABELS);
  }

  return DEFAULT_ENGLISH_LABELS;
}

/**
 * Get the label for a specific layout and slot in a given locale.
 *
 * @param layoutName - The layout name (e.g., "callout", "hero")
 * @param slotName - The slot name within the layout
 * @param locale - BCP47 locale tag (defaults to "en")
 * @returns The translated label, or empty string if not found
 */
export function slotLabel(layoutName: string, slotName: string, locale: string = "en"): string {
  const labels = slotLabels(locale);
  return labels[layoutName]?.[slotName] ?? "";
}

/**
 * Get all slot labels for a specific layout across all configured locales.
 * Useful for docs generation showing translated variants.
 *
 * @param layoutName - The layout name to look up
 * @returns Map of locale to slot labels for that layout
 */
export function slotLabelsByLocale(layoutName: string): Record<string, Record<string, string>> {
  const result: Record<string, Record<string, string>> = {};

  for (const [locale, labels] of Object.entries(LOCALE_LABELS)) {
    if (labels[layoutName]) {
      result[locale] = labels[layoutName];
    }
  }

  return result;
}

/**
 * Merge locale-specific labels with English fallbacks.
 * Ensures all slots have a label, even if not translated.
 */
function mergeWithFallback(localeLabels: SlotLabelsMap, fallback: SlotLabelsMap): SlotLabelsMap {
  const merged: SlotLabelsMap = {};

  // Ensure all layouts from fallback are present
  for (const layoutName of Object.keys(fallback)) {
    merged[layoutName] = {
      ...fallback[layoutName],
      ...localeLabels[layoutName],
    };
  }

  // Add any layouts from localeLabels not in fallback
  for (const layoutName of Object.keys(localeLabels)) {
    if (!merged[layoutName]) {
      merged[layoutName] = localeLabels[layoutName];
    }
  }

  return merged;
}

/**
 * Register a new locale with slot labels.
 * Called by i18n setup code after loading translations.
 *
 * @param locale - BCP47 locale tag
 * @param labels - Map of layout names to slot labels
 */
export function registerSlotLabels(locale: string, labels: SlotLabelsMap): void {
  LOCALE_LABELS[locale] = mergeWithFallback(labels, DEFAULT_ENGLISH_LABELS);
}

/**
 * Get all configured locales (for UI pickers, etc.).
 */
export function supportedLocales(): string[] {
  return Object.keys(LOCALE_LABELS);
}
