import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { compileCssToTs } from "../../scripts/compile-css-to-ts.ts";

function findLayoutHtmlFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) results.push(...findLayoutHtmlFiles(path));
    else if (entry.name === "layout.html") results.push(path);
  }
  return results.sort();
}

function toIdentifier(file: string, sourceDir: string): string {
  return relative(sourceDir, file)
    .replace(/\/layout\.html$/u, "")
    .split(/[/\\]/u)
    .map((segment, index) => {
      const camel = segment.replace(/-([a-z0-9])/gu, (_, character: string) =>
        character.toUpperCase(),
      );
      return index === 0 ? camel : camel.charAt(0).toUpperCase() + camel.slice(1);
    })
    .join("");
}

function compileLayoutHtmlToTs(sourceDir: string, outFile: string): void {
  const outDir = resolve(outFile, "..");
  const files = findLayoutHtmlFiles(sourceDir);
  const entries = files.map((file) => {
    const html = readFileSync(file, "utf8");
    return `export const ${toIdentifier(file, sourceDir)}Html: string = ${JSON.stringify(html)};`;
  });
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    outFile,
    `// AUTO-GENERATED by scripts/component-styles.ts — do not edit.\n${entries.join("\n")}\n`,
  );
  console.log(
    `✓ layouts: wrote ${outFile.replace(resolve(outFile, "../../../.."), "")} (${entries.length} HTML snippet(s))`,
  );
}

compileCssToTs(
  resolve(import.meta.dirname, "../src/layouts"),
  resolve(import.meta.dirname, "../src/generated/component-styles.ts"),
  "layouts",
);

compileLayoutHtmlToTs(
  resolve(import.meta.dirname, "../src/layouts"),
  resolve(import.meta.dirname, "../src/generated/layout-html.ts"),
);
