/**
 * Build-time generator for `@pantoken/plugin-font-families`. Reads the vendored woff2 files under
 * `assets/fonts/` (copied from Instructure's UX-guidelines shared assets) and writes:
 *
 * - `generated/fonts.css` — the `@font-face` rules, `src` pointing at the shipped woff2 files.
 * - `generated/embedded.ts` — the parsed font metadata plus the same CSS as a string constant, so
 *   the plugin ships it without a runtime file read.
 *
 * Fonts are referenced by URL (not inlined as data URIs) to keep the stylesheet small; the woff2
 * files ship in the package and `fonts.css` points at them relative to its own location.
 */
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const fontsDir = join(root, "assets/fonts");
const outDir = join(root, "generated");

/** A font family directory, its CSS `font-family` name, and its fallback stack. */
const FAMILIES = [
  {
    dir: "AtkinsonHyperlegibleNext",
    id: "atkinson-hyperlegible-next",
    cssName: "Atkinson Hyperlegible Next",
    fallback: "system-ui, sans-serif",
  },
] as const;

/** Weight-name (as it appears in a filename) → CSS numeric font-weight. */
const WEIGHTS: Record<string, number> = {
  Thin: 100,
  ExtraLight: 200,
  Light: 300,
  Regular: 400,
  Book: 450,
  Medium: 500,
  SemiBold: 600,
  Bold: 700,
  ExtraBold: 800,
  Black: 900,
  ExtraBlack: 950,
};
// Longest first so "ExtraBold" matches before "Bold".
const WEIGHT_NAMES = Object.keys(WEIGHTS).toSorted((a, b) => b.length - a.length);

interface FontFile {
  family: string;
  filename: string;
  path: string;
  cssWeight: number;
  style: "italic" | "normal";
}

/** Parse `<Prefix>-<Variant>.woff2` into a weight and style. */
function parseVariant(
  filename: string,
): { cssWeight: number; style: "italic" | "normal" } | undefined {
  const variant = filename.replace(/^[A-Za-z]+-/u, "").replace(/\.woff2$/u, "");
  if (variant === "Italic") return { cssWeight: 400, style: "italic" };
  for (const name of WEIGHT_NAMES) {
    if (variant.startsWith(name)) {
      const rest = variant.slice(name.length);
      if (rest === "" || rest === "Italic") {
        return { cssWeight: WEIGHTS[name], style: rest === "Italic" ? "italic" : "normal" };
      }
    }
  }
  return undefined;
}

const files: FontFile[] = [];
for (const family of FAMILIES) {
  const dir = join(fontsDir, family.dir);
  for (const filename of readdirSync(dir).toSorted()) {
    if (!filename.endsWith(".woff2")) continue;
    const parsed = parseVariant(filename);
    if (!parsed) continue;
    files.push({
      family: family.id,
      filename,
      path: `${family.dir}/${filename}`,
      cssWeight: parsed.cssWeight,
      style: parsed.style,
    });
  }
}
files.sort(
  (a, b) =>
    a.family.localeCompare(b.family) || a.cssWeight - b.cssWeight || a.style.localeCompare(b.style),
);

const cssNameOf = (id: string): string => FAMILIES.find((f) => f.id === id)?.cssName ?? id;

// `@font-face` rules, src relative to generated/fonts.css → ../assets/fonts/<dir>/<file>.
const fontFace = files
  .map((f) =>
    [
      "@font-face {",
      `  font-family: "${cssNameOf(f.family)}";`,
      `  font-style: ${f.style};`,
      `  font-weight: ${String(f.cssWeight)};`,
      "  font-display: swap;",
      `  src: url("../assets/fonts/${f.path}") format("woff2");`,
      "}",
    ].join("\n"),
  )
  .join("\n\n");

// `:root` custom properties, one per family: --instui-font-family-<id>.
const rootVars = [
  ":root {",
  ...FAMILIES.map((f) => `  --instui-font-family-${f.id}: "${f.cssName}", ${f.fallback};`),
  "}",
].join("\n");

const fontsCss = `/* Instructure brand fonts (pantoken font-families plugin) — generated, do not edit. */\n${fontFace}\n\n${rootVars}\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "fonts.css"), fontsCss);

const embedded = [
  "// GENERATED by scripts/generate.ts — do not edit by hand.",
  'import type { FontFile } from "../src/index.ts";',
  "",
  `export const FONT_FILES: FontFile[] = ${JSON.stringify(files, null, 2)};`,
  "",
  `export const FONTS_CSS = ${JSON.stringify(fontsCss)};`,
  "",
];
writeFileSync(join(outDir, "embedded.ts"), embedded.join("\n"));

console.log(`✓ font-families: ${files.length} faces across ${FAMILIES.length} families`);
