/**
 * Tests for the `@pantoken/plugin-custom-icons` build-time generator (`scripts/generate.ts`).
 *
 * The generator reads SVG files from `assets/icons/<name>.svg` and writes per-icon
 * `generated/icons/<name>.css`, the `generated/custom-icons.css` barrel, and `generated/embedded.ts`.
 * All filesystem I/O is mocked so this suite runs without touching disk and each test reimports the
 * module in a clean state.
 *
 * @module
 */
import { afterEach, beforeEach, describe, expect, test, vi } from "vite-plus/test";

const readFileSync = vi.fn<(...args: unknown[]) => string>();
const writeFileSync = vi.fn();
const mkdirSync = vi.fn();
const readdirSync = vi.fn<(...args: unknown[]) => string[]>();

vi.mock("node:fs", () => ({ readFileSync, writeFileSync, mkdirSync, readdirSync }));

const MODULE_PATH = new URL("./generate.ts", import.meta.url).pathname;

beforeEach(() => {
  vi.resetModules();
  vi.clearAllMocks();
  readdirSync.mockReturnValue(["highspot.svg"]);
  readFileSync.mockReturnValue(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill="currentColor" d="M8 0"/></svg>',
  );
  vi.spyOn(console, "log").mockImplementation(() => {});
});

afterEach(() => {
  vi.restoreAllMocks();
});

/** Extract the content argument of the `writeFileSync` call whose path ends with `suffix`. */
function writtenContent(suffix: string): string {
  const call = writeFileSync.mock.calls.find(([p]) => String(p).endsWith(suffix));
  return call ? String(call[1]) : "";
}

describe("per-icon CSS", () => {
  test("declares the --instui-icon-<name> token and .-icon-<name> painter hookup", async () => {
    await import(MODULE_PATH);
    const css = writtenContent("/icons/highspot.css");
    expect(css).toContain("--instui-icon-highspot:url(");
    expect(css).toContain(".-icon-highspot{--pantoken-glyph:var(--instui-icon-highspot)}");
  });

  test("does not use a custom- prefix — collisions favour the built-in icon", async () => {
    await import(MODULE_PATH);
    const css = writtenContent("/icons/highspot.css");
    expect(css).not.toContain("custom-icon");
  });

  test("encodes the SVG as a utf8 (non-base64) data URI", async () => {
    await import(MODULE_PATH);
    const css = writtenContent("/icons/highspot.css");
    expect(css).toContain("data:image/svg+xml;utf8,");
  });
});

describe("generated custom-icons.css barrel", () => {
  test("concatenates every per-icon sheet", async () => {
    readdirSync.mockReturnValue(["highspot.svg", "acme.svg"]);
    await import(MODULE_PATH);
    const css = writtenContent("custom-icons.css");
    expect(css).toContain("--instui-icon-acme:");
    expect(css).toContain("--instui-icon-highspot:");
  });

  test("ignores non-SVG files in the assets directory", async () => {
    readdirSync.mockReturnValue(["highspot.svg", ".DS_Store", "readme.txt"]);
    await import(MODULE_PATH);
    expect(writeFileSync.mock.calls.some(([p]) => String(p).endsWith("readme.txt.css"))).toBe(
      false,
    );
  });
});

describe("generated embedded.ts", () => {
  test("writes the generated-file header and exports ICONS", async () => {
    await import(MODULE_PATH);
    const ts = writtenContent("embedded.ts");
    expect(ts).toContain("// GENERATED by scripts/generate.ts");
    expect(ts).toContain("export const ICONS");
    expect(ts).toContain('"name": "highspot"');
  });

  test("icons are sorted alphabetically by name", async () => {
    readdirSync.mockReturnValue(["highspot.svg", "acme.svg"]);
    await import(MODULE_PATH);
    const ts = writtenContent("embedded.ts");
    expect(ts.indexOf('"acme"')).toBeLessThan(ts.indexOf('"highspot"'));
  });
});

describe("console output", () => {
  test("logs the icon count", async () => {
    const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});
    readdirSync.mockReturnValue(["highspot.svg", "acme.svg"]);
    await import(MODULE_PATH);
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining("wrote 2 per-icon CSS files"));
  });
});
