/**
 * Emit the custom-icons CSS output: per-icon stylesheets and a full barrel, plus the embedded
 * metadata module `src/index.ts` imports from.
 *
 * Each `generated/icons/<name>.css` is self-contained — it declares the `--instui-icon-<name>`
 * custom property (as a data-URI) and the `.-icon-<name>` glyph modifier, the same shared painter
 * class the InstUI icon set and Simple Icons use. No `custom-` prefix: a custom icon is meant to
 * drop into `.instui-icon -icon-<name>` exactly like a built-in one. On a name collision, the
 * built-in InstUI icon should win — load `custom-icons.css` (or a per-icon file) *before* the
 * InstUI icon sheet in any combine URL, since `:root` custom properties resolve last-wins.
 *
 * `generated/custom-icons.css` is the full barrel (every vendored icon concatenated) for
 * consumers who want them all in one request.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const iconsSrcDir = join(root, "assets/icons");
const outDir = join(root, "generated");
const iconsOutDir = join(outDir, "icons");
mkdirSync(iconsOutDir, { recursive: true });

interface CustomIcon {
  name: string;
  svg: string;
}

const icons: CustomIcon[] = readdirSync(iconsSrcDir)
  .filter((f) => f.endsWith(".svg"))
  .map((f) => ({
    name: f.replace(/\.svg$/u, ""),
    svg: readFileSync(join(iconsSrcDir, f), "utf8").trim(),
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const barrel: string[] = [];
for (const icon of icons) {
  const dataUri = `url('data:image/svg+xml;utf8,${encodeURIComponent(icon.svg)}')`;
  const css = `:root{--instui-icon-${icon.name}:${dataUri}}.-icon-${icon.name}{--pantoken-glyph:var(--instui-icon-${icon.name})}\n`;
  writeFileSync(join(iconsOutDir, `${icon.name}.css`), css);
  barrel.push(css);
}
writeFileSync(join(outDir, "custom-icons.css"), barrel.join(""));

const embedded = [
  "// GENERATED by scripts/generate.ts — do not edit by hand.",
  'import type { CustomIcon } from "../src/index.ts";',
  "",
  `export const ICONS: CustomIcon[] = ${JSON.stringify(icons, null, 2)};`,
  "",
].join("\n");
writeFileSync(join(outDir, "embedded.ts"), embedded);

console.log(`✓ custom-icons: wrote ${icons.length} per-icon CSS files + custom-icons.css barrel`);
