// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Arabic (العربية) locale bundle. */
export const ar: LocaleBundle = defineBundle({
  locale: "ar",
  dir: "rtl",
  label: "Arabic (العربية)",
  strings: makeStrings("ar", {
    prevMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    dateLabel: "التاريخ",
    openCalendar: "افتح التقويم",
    timeLabel: "الوقت",
    back: "رجوع",
  }),
});
