// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Catalan (Catalá) locale bundle. */
export const ca: LocaleBundle = defineBundle({
  locale: "ca",
  dir: "ltr",
  label: "Catalan (Catalá)",
  strings: makeStrings("ca", {
    prevMonth: "Mes anterior",
    nextMonth: "Mes següent",
    dateLabel: "Data",
    openCalendar: "Obrir el calendari",
    timeLabel: "Hora",
    back: "Enrere",
  }),
});
