// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Welsh (Cymraeg) locale bundle. */
export const cy: LocaleBundle = defineBundle({
  locale: "cy",
  dir: "ltr",
  label: "Welsh (Cymraeg)",
  strings: makeStrings("cy", {
    prevMonth: "Mis blaenorol",
    nextMonth: "Mis nesaf",
    dateLabel: "Dyddiad",
    openCalendar: "Agor calendr",
    timeLabel: "Amser",
    back: "Yn ôl",
  }),
});
