// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** German (Deutsch) locale bundle. */
export const de: LocaleBundle = defineBundle({
  locale: "de",
  dir: "ltr",
  label: "German (Deutsch)",
  strings: makeStrings("de", {
    prevMonth: "Vorheriger Monat",
    nextMonth: "Nächster Monat",
    dateLabel: "Datum",
    openCalendar: "Kalender öffnen",
    timeLabel: "Uhrzeit",
    back: "Zurück",
  }),
});
