// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** English (Australia) locale bundle. */
export const enAU: LocaleBundle = defineBundle({
  locale: "en-AU",
  dir: "ltr",
  label: "English (Australia)",
  strings: makeStrings("en-AU", {
    datePlaceholder: "dd/mm/yyyy",
  }),
});
