// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** English (Canada) locale bundle. */
export const enCA: LocaleBundle = defineBundle({
  locale: "en-CA",
  dir: "ltr",
  label: "English (Canada)",
  strings: makeStrings("en-CA"),
});
