// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** English (United Kingdom) locale bundle. */
export const enGB: LocaleBundle = defineBundle({
  locale: "en-GB",
  dir: "ltr",
  label: "English (United Kingdom)",
  strings: makeStrings("en-GB"),
});
