// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** English (United States) locale bundle. */
export const en: LocaleBundle = defineBundle({
  locale: "en",
  dir: "ltr",
  label: "English (United States)",
  strings: makeStrings("en"),
});
