// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Spanish (Español) locale bundle. */
export const es: LocaleBundle = defineBundle({
  locale: "es",
  dir: "ltr",
  label: "Spanish (Español)",
  strings: makeStrings("es", {
    prevMonth: "Mes anterior",
    nextMonth: "Mes siguiente",
    dateLabel: "Fecha",
    openCalendar: "Abrir calendario",
    timeLabel: "Hora",
    back: "Atrás",
  }),
});
