// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Finnish (Suomi) locale bundle. */
export const fi: LocaleBundle = defineBundle({
  locale: "fi",
  dir: "ltr",
  label: "Finnish (Suomi)",
  strings: makeStrings("fi", {
    prevMonth: "Edellinen kuukausi",
    nextMonth: "Seuraava kuukausi",
    dateLabel: "Päivämäärä",
    openCalendar: "Avaa kalenteri",
    timeLabel: "Aika",
    back: "Takaisin",
  }),
});
