// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** French Canadian (Français Canada) locale bundle. */
export const frCA: LocaleBundle = defineBundle({
  locale: "fr-CA",
  dir: "ltr",
  label: "French Canadian (Français Canada)",
  strings: makeStrings("fr-CA", {
    prevMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    openCalendar: "Ouvrir le calendrier",
    timeLabel: "Heure",
    back: "Retour",
  }),
});
