// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** French (Français) locale bundle. */
export const fr: LocaleBundle = defineBundle({
  locale: "fr",
  dir: "ltr",
  label: "French (Français)",
  strings: makeStrings("fr", {
    prevMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    openCalendar: "Ouvrir le calendrier",
    timeLabel: "Heure",
    back: "Retour",
  }),
});
