// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Irish Gaelic locale bundle. */
export const ga: LocaleBundle = defineBundle({
  locale: "ga",
  dir: "ltr",
  label: "Irish Gaelic",
  strings: makeStrings("ga", {
    prevMonth: "Mí roimhe",
    nextMonth: "Mí ina dhiaidh",
    dateLabel: "Dáta",
    openCalendar: "Oscail an fhéilire",
    timeLabel: "Am",
    back: "Ar ais",
  }),
});
