// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Hebrew (עִברִית) locale bundle. */
export const he: LocaleBundle = defineBundle({
  locale: "he",
  dir: "rtl",
  label: "Hebrew (עִברִית)",
  strings: makeStrings("he", {
    prevMonth: "החודש הקודם",
    nextMonth: "החודש הבא",
    dateLabel: "תאריך",
    openCalendar: "פתח לוח שנה",
    timeLabel: "שעה",
    back: "חזור",
  }),
});
