// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Hindi (हिन्दी) locale bundle. */
export const hi: LocaleBundle = defineBundle({
  locale: "hi",
  dir: "ltr",
  label: "Hindi (हिन्दी)",
  strings: makeStrings("hi", {
    prevMonth: "पिछला महीना",
    nextMonth: "अगला महीना",
    dateLabel: "दिनांक",
    openCalendar: "कैलेंडर खोलें",
    timeLabel: "समय",
    back: "वापस",
  }),
});
