// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Haitian Creole (Kreyòl Ayisyen) locale bundle. */
export const ht: LocaleBundle = defineBundle({
  locale: "ht",
  dir: "ltr",
  label: "Haitian Creole (Kreyòl Ayisyen)",
  strings: makeStrings("ht", {
    prevMonth: "Mwa presedan",
    nextMonth: "Mwa pwochen",
    dateLabel: "Dat",
    openCalendar: "Ouvri kalandriye",
    timeLabel: "Lè",
    back: "Retounen",
  }),
});
