// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Hungarian (Magyar) locale bundle. */
export const hu: LocaleBundle = defineBundle({
  locale: "hu",
  dir: "ltr",
  label: "Hungarian (Magyar)",
  strings: makeStrings("hu", {
    prevMonth: "Előző hónap",
    nextMonth: "Következő hónap",
    dateLabel: "Dátum",
    datePlaceholder: "éééé-hh-nn",
    openCalendar: "Naptár megnyitása",
    timeLabel: "Idő",
    back: "Vissza",
  }),
});
