// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Armenian (Հայերեն) locale bundle. */
export const hy: LocaleBundle = defineBundle({
  locale: "hy",
  dir: "ltr",
  label: "Armenian (Հայերեն)",
  strings: makeStrings("hy", {
    prevMonth: "Նախորդ ամիս",
    nextMonth: "Հաջորդ ամիս",
    dateLabel: "Ամսաթիվ",
    openCalendar: "Բացել օրացույցը",
    timeLabel: "Ժամ",
    back: "Հետ",
  }),
});
