// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Icelandic (Íslenska) locale bundle. */
export const is: LocaleBundle = defineBundle({
  locale: "is",
  dir: "ltr",
  label: "Icelandic (Íslenska)",
  strings: makeStrings("is", {
    prevMonth: "Fyrri mánuður",
    nextMonth: "Næsti mánuður",
    dateLabel: "Dagsetning",
    openCalendar: "Opna dagatal",
    timeLabel: "Tími",
    back: "Til baka",
  }),
});
