// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Korean (한국말) locale bundle. */
export const ko: LocaleBundle = defineBundle({
  locale: "ko",
  dir: "ltr",
  label: "Korean (한국말)",
  strings: makeStrings("ko", {
    prevMonth: "이전 달",
    nextMonth: "다음 달",
    dateLabel: "날짜",
    openCalendar: "달력 열기",
    timeLabel: "시간",
    back: "뒤로",
  }),
});
