// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Malaysian (Bahasa Melayu) locale bundle. */
export const ms: LocaleBundle = defineBundle({
  locale: "ms",
  dir: "ltr",
  label: "Malaysian (Bahasa Melayu)",
  strings: makeStrings("ms", {
    prevMonth: "Bulan sebelumnya",
    nextMonth: "Bulan seterusnya",
    dateLabel: "Tarikh",
    openCalendar: "Buka kalendar",
    timeLabel: "Masa",
    back: "Kembali",
  }),
});
