// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Norwegian Bokmål (Norsk Bokmål) locale bundle. */
export const nb: LocaleBundle = defineBundle({
  locale: "nb",
  dir: "ltr",
  label: "Norwegian Bokmål (Norsk Bokmål)",
  strings: makeStrings("nb", {
    prevMonth: "Forrige måned",
    nextMonth: "Neste måned",
    dateLabel: "Dato",
    openCalendar: "Åpne kalender",
    timeLabel: "Tid",
    back: "Tilbake",
  }),
});
