// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Norwegian Nynorsk (Norsk Nynorsk) locale bundle. */
export const nn: LocaleBundle = defineBundle({
  locale: "nn",
  dir: "ltr",
  label: "Norwegian Nynorsk (Norsk Nynorsk)",
  strings: makeStrings("nn", {
    prevMonth: "Førre månad",
    nextMonth: "Neste månad",
    dateLabel: "Dato",
    openCalendar: "Opna kalender",
    timeLabel: "Tid",
    back: "Tilbake",
  }),
});
