// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Portuguese (Português) locale bundle. */
export const pt: LocaleBundle = defineBundle({
  locale: "pt",
  dir: "ltr",
  label: "Portuguese (Português)",
  strings: makeStrings("pt", {
    prevMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    dateLabel: "Data",
    openCalendar: "Abrir calendário",
    timeLabel: "Hora",
    back: "Voltar",
  }),
});
