// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Russian (Русский) locale bundle. */
export const ru: LocaleBundle = defineBundle({
  locale: "ru",
  dir: "ltr",
  label: "Russian (Русский)",
  strings: makeStrings("ru", {
    prevMonth: "Предыдущий месяц",
    nextMonth: "Следующий месяц",
    dateLabel: "Дата",
    openCalendar: "Открыть календарь",
    timeLabel: "Время",
    back: "Назад",
  }),
});
