// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Northern Sami locale bundle. */
export const se: LocaleBundle = defineBundle({
  locale: "se",
  dir: "ltr",
  label: "Northern Sami",
  strings: makeStrings("se", {
    prevMonth: "Ovtta mánnu",
    nextMonth: "Maŋŋel mánnu",
    dateLabel: "Dátuma",
    datePlaceholder: "åååå-mm-dd",
    openCalendar: "Ávnnat kalendára",
    timeLabel: "Áigi",
    back: "Boađe",
  }),
});
