// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Slovenian (Slovenščina) locale bundle. */
export const sl: LocaleBundle = defineBundle({
  locale: "sl",
  dir: "ltr",
  label: "Slovenian (Slovenščina)",
  strings: makeStrings("sl", {
    prevMonth: "Prejšnji mesec",
    nextMonth: "Naslednji mesec",
    dateLabel: "Datum",
    openCalendar: "Odpri koledar",
    timeLabel: "Čas",
    back: "Nazaj",
  }),
});
