// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Swedish (Svenska) locale bundle. */
export const sv: LocaleBundle = defineBundle({
  locale: "sv",
  dir: "ltr",
  label: "Swedish (Svenska)",
  strings: makeStrings("sv", {
    prevMonth: "Föregående månad",
    nextMonth: "Nästa månad",
    dateLabel: "Datum",
    openCalendar: "Öppna kalender",
    timeLabel: "Tid",
    back: "Tillbaka",
  }),
});
