// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Turkish (Türkçe) locale bundle. */
export const tr: LocaleBundle = defineBundle({
  locale: "tr",
  dir: "ltr",
  label: "Turkish (Türkçe)",
  strings: makeStrings("tr", {
    prevMonth: "Önceki ay",
    nextMonth: "Sonraki ay",
    dateLabel: "Tarih",
    openCalendar: "Takvimi aç",
    timeLabel: "Saat",
    back: "Geri",
  }),
});
