// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Simplified Chinese (简体中文) locale bundle. */
export const zhHans: LocaleBundle = defineBundle({
  locale: "zh-Hans",
  dir: "ltr",
  label: "Simplified Chinese (简体中文)",
  strings: makeStrings("zh-Hans", {
    prevMonth: "上一月",
    nextMonth: "下一月",
    dateLabel: "日期",
    openCalendar: "打开日历",
    timeLabel: "时间",
    back: "返回",
  }),
});
