/**
 * Emit the pantoken IR as Stylus variables. Values are resolved to concrete, single-mode values so
 * the output is a self-contained Stylus token file (`instui-color-brand = #0374b5`). Icon tokens are
 * skipped — they belong in CSS, not Stylus variables.
 *
 * @module
 */
import { resolveTokens } from "@pantoken/utils";
import type { Mode } from "@pantoken/utils";
import type { Token } from "@pantoken/model";

export type { Mode } from "@pantoken/utils";

/** Options for {@link toStylus}. */
export interface ToStylusOptions {
  /** Which colour mode to resolve (default `"light"`). */
  mode?: Mode;
}

/**
 * Emit Stylus variables for a token IR.
 *
 * @param tokens - The IR (e.g. from `@pantoken/tokens`).
 * @param options - {@link ToStylusOptions}.
 * @returns The Stylus source string.
 *
 * @example Emit the default (light) variables
 * ```ts
 * import { toStylus } from "@pantoken/stylus";
 * import { tokens } from "@pantoken/tokens";
 *
 * toStylus(tokens); // "instui-color-brand = #0374b5\n…"
 * ```
 *
 * @example Resolve the dark mode of another theme
 * ```ts
 * import { toStylus } from "@pantoken/stylus";
 * import { byTheme } from "@pantoken/tokens";
 *
 * toStylus(byTheme("canvas"), { mode: "dark" });
 * ```
 */
export function toStylus(tokens: readonly Token[], options: ToStylusOptions = {}): string {
  const resolved = resolveTokens(tokens, { mode: options.mode ?? "light" });
  const lines = ["// DO NOT EDIT — generated by @pantoken/stylus", ""];
  for (const token of tokens) {
    if (token.meta?.kind === "icon") continue;
    lines.push(`${token.name.replace(/^--/, "")} = ${resolved.get(token.name) ?? token.value}`);
  }
  return `${lines.join("\n")}\n`;
}
