/**
 * The aggregator for the unified `pantoken` meta package. It scans the meta package's dependencies
 * for the `pantoken` field, then generates the barrel (`export * as <key> from "<pkg>"`), one
 * subpath entry file per target, and the meta `package.json` `exports` map — so adding a new target
 * package with a `pantoken` field auto-registers it, with no manual barrel edits.
 *
 * @module
 */
import { createRequire } from "node:module";
import { join } from "node:path";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

/** A target discovered by its `pantoken` field. */
export interface Target {
  /** The package name, e.g. `@pantoken/astro`. */
  pkg: string;
  /** The aggregation key / export name, e.g. `astro`. */
  key: string;
  /**
   * How the target is exposed:
   * - `namespace` — re-exported into the eager barrel *and* as a subpath.
   * - `sideEffect` — subpath imports the package's `/inject` entry; also in the barrel.
   * - `subpath` — subpath only, kept OUT of the eager barrel (for heavy peers like React, so
   *   `import "pantoken"` never loads them).
   */
  kind: "namespace" | "sideEffect" | "subpath";
}

/** Options for {@link aggregate}. */
export interface AggregateOptions {
  /** The meta package directory (contains `package.json` and `src/`). */
  metaDir: string;
}

/**
 * Read the `pantoken` targets from the meta package's dependencies.
 *
 * @example Inspect what would be aggregated, without writing anything
 * ```ts
 * import { discoverTargets } from "@pantoken/aggregate";
 *
 * const targets = discoverTargets("/path/to/packages/pantoken");
 * for (const t of targets) console.log(t.key, t.kind, "->", t.pkg);
 * ```
 */
export function discoverTargets(metaDir: string): Target[] {
  const require = createRequire(join(metaDir, "package.json"));
  const meta = JSON.parse(readFileSync(join(metaDir, "package.json"), "utf8"));
  const deps = Object.keys(meta.dependencies ?? {});
  const targets: Target[] = [];
  for (const pkg of deps) {
    let manifest: { pantoken?: { key?: string; kind?: string } };
    try {
      manifest = JSON.parse(readFileSync(require.resolve(`${pkg}/package.json`), "utf8"));
    } catch {
      continue;
    }
    const field = manifest.pantoken;
    if (!field?.key) continue;
    const kind =
      field.kind === "sideEffect"
        ? "sideEffect"
        : field.kind === "subpath"
          ? "subpath"
          : "namespace";
    targets.push({ pkg, key: field.key, kind });
  }
  return targets.sort((a, b) => (a.key < b.key ? -1 : 1));
}

/** Clear previously-generated `src/*.ts` files (keeps the dir clean between runs). */
function clearGenerated(srcDir: string): void {
  for (const file of readdirSync(srcDir)) {
    if (file.endsWith(".ts")) writeFileSync(join(srcDir, file), "", { flag: "w" });
  }
}

/**
 * Generate the meta package's source barrel, subpath entries, and `exports` map.
 *
 * @param options - {@link AggregateOptions}.
 * @returns The discovered targets.
 *
 * @example Regenerate the meta package
 * ```ts
 * import { aggregate } from "@pantoken/aggregate";
 *
 * const targets = aggregate({ metaDir: "/path/to/packages/pantoken" });
 * // writes src/index.ts (barrel), src/<key>.ts (subpaths), and rewrites package.json exports
 * console.log(`aggregated ${targets.length} targets`);
 * ```
 */
export function aggregate(options: AggregateOptions): Target[] {
  const { metaDir } = options;
  const srcDir = join(metaDir, "src");
  const targets = discoverTargets(metaDir);

  clearGenerated(srcDir);

  // Barrel: namespace-export every target EXCEPT subpath-only ones (whose heavy peers must not be
  // loaded by `import "pantoken"`), so `import { astro } from "pantoken"` works.
  const header = "// GENERATED by @pantoken/aggregate — do not edit by hand.\n";
  const barrel = [
    header,
    ...targets
      .filter((t) => t.kind !== "subpath")
      .map((t) => `export * as ${t.key} from "${t.pkg}";`),
    "",
  ].join("\n");
  writeFileSync(join(srcDir, "index.ts"), barrel);

  // One subpath entry per target: `pantoken/<key>` mirrors the standalone package.
  const exportsMap: Record<string, string> = { ".": "./dist/index.mjs" };
  for (const t of targets) {
    const body =
      t.kind === "sideEffect"
        ? `${header}import "${t.pkg}/inject";\nexport * from "${t.pkg}";\n`
        : `${header}export * from "${t.pkg}";\n`;
    writeFileSync(join(srcDir, `${t.key}.ts`), body);
    exportsMap[`./${t.key}`] = `./dist/${t.key}.mjs`;
  }
  exportsMap["./package.json"] = "./package.json";

  // Rewrite the meta package.json exports map, preserving everything else.
  const metaPkgPath = join(metaDir, "package.json");
  const metaPkg = JSON.parse(readFileSync(metaPkgPath, "utf8"));
  metaPkg.exports = exportsMap;
  writeFileSync(metaPkgPath, `${JSON.stringify(metaPkg, null, 2)}\n`);

  return targets;
}
