/**
 * `@pantoken/rust` — emit Instructure design tokens as Rust constants for the two mainstream native
 * Rust GUIs: **egui** (`Color32`) and **iced** (`Color`). Colours become the framework's colour
 * type; dimensions become `f32` (px). Web-rendered Rust UIs (Tauri, Dioxus-web, Leptos, Yew) should
 * use `@pantoken/css` instead.
 *
 * @module
 * @experimental
 */
import { toStyleDictionary } from "@pantoken/core";
import { byTheme } from "@pantoken/tokens";
import { parseHexColor } from "@pantoken/utils";
import type { Mode } from "@pantoken/core";
import type { Theme, Token } from "@pantoken/model";

/** The Rust GUI framework to target. */
export type RustFormat = "egui" | "iced";

interface Rgb {
  r: number;
  g: number;
  b: number;
  a: number;
}

function hexToRgb(hex: string): Rgb | undefined {
  const c = parseHexColor(hex);
  // parseHexColor's alpha is 0–1; rust's channels (incl. alpha) are 0–255.
  return c ? { r: c.r, g: c.g, b: c.b, a: Math.round(c.a * 255) } : undefined;
}

function constName(tokenName: string): string {
  return tokenName
    .replace(/^--instui-/, "")
    .replace(/-/g, "_")
    .toUpperCase();
}

function dimension(value: string): number | undefined {
  const m = /^(-?\d*\.?\d+)(px|rem|em)?$/.exec(value.trim());
  if (!m) return undefined;
  return Number(m[1]) * (m[2] === "rem" || m[2] === "em" ? 16 : 1);
}

/** Options for {@link toRust} / {@link generateRust}. */
export interface RustOptions {
  /** The Rust GUI to target (default `"egui"`). */
  format?: RustFormat;
  /** Which `light-dark()` mode to resolve (default `"light"`). */
  mode?: Mode;
}

/** Format a number as a Rust `f32` literal (always with a decimal, so `1` → `1.0`). */
function f32lit(n: number): string {
  return Number.isInteger(n) ? `${n}.0` : `${n}`;
}

function colorLiteral(format: RustFormat, rgb: Rgb): { ty: string; expr: string } {
  if (format === "egui") {
    const expr =
      rgb.a === 255
        ? `Color32::from_rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`
        : `Color32::from_rgba_unmultiplied(${rgb.r}, ${rgb.g}, ${rgb.b}, ${rgb.a})`;
    return { ty: "Color32", expr };
  }
  const c = (n: number): string => f32lit(n / 255);
  return {
    ty: "Color",
    expr: `Color { r: ${c(rgb.r)}, g: ${c(rgb.g)}, b: ${c(rgb.b)}, a: ${c(rgb.a)} }`,
  };
}

/**
 * Emit Rust constants for an explicit token IR.
 *
 * @param tokens - The IR.
 * @param options - {@link RustOptions}.
 * @returns The Rust source (a module of `pub const`s).
 *
 * @example egui (Color32), the default format
 * ```ts
 * import { toRust } from "@pantoken/rust";
 * import { byTheme } from "@pantoken/tokens";
 *
 * const source = toRust(byTheme("rebrand"));
 * // "use egui::Color32;\npub const COLOR_BACKGROUND_BRAND: Color32 = Color32::from_rgb(…);"
 * ```
 *
 * @example iced (Color), dark mode
 * ```ts
 * import { toRust } from "@pantoken/rust";
 * import { byTheme } from "@pantoken/tokens";
 *
 * const source = toRust(byTheme("rebrand"), { format: "iced", mode: "dark" });
 * // "use iced::Color;\npub const COLOR_BACKGROUND_BRAND: Color = Color { r: …, g: …, b: …, a: … };"
 * ```
 */
export function toRust(tokens: readonly Token[], options: RustOptions = {}): string {
  const format = options.format ?? "egui";
  const dictionary = toStyleDictionary(tokens, options.mode ?? "light");

  const lines: string[] = [
    "// GENERATED by @pantoken/rust — do not edit by hand.",
    "#![allow(dead_code)]",
    format === "egui" ? "use egui::Color32;" : "use iced::Color;",
    "",
  ];

  for (const [name, leaf] of Object.entries(dictionary)) {
    const constant = constName(`--${name}`);
    if (leaf.type === "color") {
      const rgb = hexToRgb(leaf.value);
      if (!rgb) continue;
      const { ty, expr } = colorLiteral(format, rgb);
      lines.push(`pub const ${constant}: ${ty} = ${expr};`);
    } else if (leaf.type === "dimension" || leaf.type === "number") {
      const n = dimension(leaf.value);
      if (n === undefined) continue;
      lines.push(`pub const ${constant}: f32 = ${f32lit(n)};`);
    }
  }

  return `${lines.join("\n")}\n`;
}

/**
 * Emit Rust constants for a named theme (using the vendored `@pantoken/tokens` IR).
 *
 * @example
 * ```ts
 * import { writeFileSync } from "node:fs";
 * import { generateRust } from "@pantoken/rust";
 *
 * writeFileSync("tokens.rs", generateRust({ format: "egui", theme: "rebrand" }));
 * ```
 */
export function generateRust(options: RustOptions & { theme?: Theme } = {}): string {
  return toRust(byTheme(options.theme ?? "rebrand"), options);
}

export default generateRust;
