/**
 * Generate `src/locales/{locale}.ts` files from the committed `i18n-cache/*.json` translation
 * memory. Run via `pnpm generate` or `vp run @pantoken/i18n#generate`.
 *
 * Strings absent from a locale's cache fall back to the English source value. Weekday names are
 * always derived at runtime via `Intl.DateTimeFormat` — they are not committed to the cache.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CANVAS_LOCALES } from "../src/lib/canvas-locales.ts";
import { keyFor } from "./lib/translation-memory.ts";
import { ENGLISH_SOURCES, TRANSLATABLE_KEYS } from "./lib/keys.ts";

const root = new URL("..", import.meta.url).pathname;
const cacheDir = join(root, "i18n-cache");
const localesDir = join(root, "src", "locales");
mkdirSync(localesDir, { recursive: true });

interface CacheFile {
  version: number;
  entries: Record<string, string>;
}

function loadCache(locale: string): Record<string, string> {
  const path = join(cacheDir, `${locale}.json`);
  if (!existsSync(path)) return {};
  return (JSON.parse(readFileSync(path, "utf8")) as CacheFile).entries ?? {};
}

/** Derive the JS identifier used in the export (handles subtag locales like en-AU → enAU). */
function toIdentifier(locale: string): string {
  return locale.replace(/-([a-zA-Z])/g, (_, c: string) => c.toUpperCase());
}

/** Produce a TS locale file for `locale`. */
// fallow-ignore-next-line complexity
function buildLocaleFile(locale: string): string {
  const meta = CANVAS_LOCALES[locale]!;
  const entries = loadCache(locale);
  const id = toIdentifier(locale);

  // Collect only strings that differ from the English source (true translations).
  const overrides: Record<string, string> = {};
  for (const key of TRANSLATABLE_KEYS) {
    const cacheKey = keyFor(key, ENGLISH_SOURCES[key]);
    const translated = entries[cacheKey];
    if (translated !== undefined && translated !== ENGLISH_SOURCES[key]) {
      overrides[key] = translated;
    }
  }

  const hasOverrides = Object.keys(overrides).length > 0;
  const stringsArg = hasOverrides
    ? `, {\n${Object.entries(overrides)
        .map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
        .join("\n")}\n  }`
    : "";

  return `// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** ${meta.label} locale bundle. */
export const ${id}: LocaleBundle = defineBundle({
  locale: ${JSON.stringify(locale)},
  dir: ${JSON.stringify(meta.dir)},
  label: ${JSON.stringify(meta.label)},
  strings: makeStrings(${JSON.stringify(locale)}${stringsArg}),
});
`;
}

const locales = Object.keys(CANVAS_LOCALES);
for (const locale of locales) {
  const content = buildLocaleFile(locale);
  const id = toIdentifier(locale);
  writeFileSync(join(localesDir, `${locale}.ts`), content);
  console.log(`  ${locale} → src/locales/${locale}.ts (${id})`);
}

console.log(`\n✓ i18n build-bundles: wrote ${locales.length} locale files`);
