/**
 * Generate `src/locales/{locale}.ts` files from `@pantoken/web-components`'s committed
 * `i18n-cache/*.json` translation memory (that package owns the source-of-truth English strings
 * and their translations; this script only reshapes them into this package's `LocaleBundle`s).
 * Run via `pnpm generate` or `vp run @pantoken/i18n#generate`.
 *
 * Strings absent from a locale's cache fall back to the English source value. Weekday names are
 * always derived at runtime via `Intl.DateTimeFormat` — they are not committed to the cache.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ENGLISH_STRINGS } from "@pantoken/web-components";
import { LOCALES } from "../src/lib/locales.ts";

// This bundle only carries `WebComponentStrings` (`weekdays` is derived at runtime, not a key).
const WEB_COMPONENT_KEYS = Object.keys(ENGLISH_STRINGS).filter((k) => k !== "weekdays");

const root = new URL("..", import.meta.url).pathname;
const cacheDir = join(root, "..", "..", "renderers", "web-components", "i18n-cache");
const localesDir = join(root, "src", "locales");
mkdirSync(localesDir, { recursive: true });

function loadCache(locale: string): Record<string, string> {
  const path = join(cacheDir, `${locale}.json`);
  if (!existsSync(path)) return {};
  return JSON.parse(readFileSync(path, "utf8"));
}

const englishSources = loadCache("en");

/** Derive the JS identifier used in the export (handles subtag locales like en-AU → enAU). */
export function toIdentifier(locale: string): string {
  return locale.replace(/-([a-zA-Z])/g, (_, c: string) => c.toUpperCase());
}

/** Produce a TS locale file for `locale`. */
export function buildLocaleFile(locale: string): string {
  const meta = LOCALES[locale]!;
  const entries = loadCache(locale);
  const id = toIdentifier(locale);

  // Collect only strings that differ from the English source (true translations).
  const overrides: Record<string, string> = {};
  for (const key of WEB_COMPONENT_KEYS) {
    const translated = entries[key];
    if (translated !== undefined && translated !== englishSources[key]) {
      overrides[key] = translated;
    }
  }

  const hasOverrides = Object.keys(overrides).length > 0;
  const stringsArg = hasOverrides
    ? `, {\n${Object.entries(overrides)
        .map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
        .join("\n")}\n  }`
    : "";

  return `// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** ${meta.label} locale bundle. */
export const ${id}: LocaleBundle = defineBundle({
  locale: ${JSON.stringify(locale)},
  dir: ${JSON.stringify(meta.dir)},
  label: ${JSON.stringify(meta.label)},
  strings: makeStrings(${JSON.stringify(locale)}${stringsArg}),
});
`;
}

const locales = Object.keys(LOCALES);
for (const locale of locales) {
  const content = buildLocaleFile(locale);
  const id = toIdentifier(locale);
  writeFileSync(join(localesDir, `${locale}.ts`), content);
  console.log(`  ${locale} → src/locales/${locale}.ts (${id})`);
}

console.log(`\n✓ i18n build-bundles: wrote ${locales.length} locale files`);
