/**
 * Generate `src/locales/{locale}.ts` files from the `ui.strings` PO catalogs the `i18n-engine`
 * pipeline maintains (`l10n/{locale}/ui.strings.po`, keyed by `msgctxt`, sourced from
 * `renderers/web-components/src/i18n.json`). Run via `pnpm generate` or
 * `vp run @pantoken/i18n#generate`.
 *
 * A key untranslated (or `translate: "never"`) in a locale's PO falls back to the English source
 * value. Weekday names are always derived at runtime via `Intl.DateTimeFormat` — never committed.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadConfig, resolveMessagesForLocale } from "@pantoken/i18n-engine";
import { ENGLISH_STRINGS } from "@pantoken/web-components";
import { LOCALES } from "../src/lib/locales.ts";

// This bundle only carries `WebComponentStrings` (`weekdays` is derived at runtime, not a key).
const WEB_COMPONENT_KEYS = Object.keys(ENGLISH_STRINGS).filter((k) => k !== "weekdays");

const root = new URL("..", import.meta.url).pathname;
const repoRoot = join(root, "..", "..");
const localesDir = join(root, "src", "locales");
mkdirSync(localesDir, { recursive: true });

const config = loadConfig(join(repoRoot, "i18n.config.json"));

function loadStrings(locale: string): Record<string, string> {
  if (locale === "en") return {}; // en is the source; nothing to resolve against
  return resolveMessagesForLocale(config, repoRoot, "ui.strings", locale).strings;
}

const englishSources: Record<string, string> = Object.fromEntries(
  WEB_COMPONENT_KEYS.map((k) => [k, ENGLISH_STRINGS[k as keyof typeof ENGLISH_STRINGS] as string]),
);

/** Derive the JS identifier used in the export (handles subtag locales like en-AU → enAU). */
export function toIdentifier(locale: string): string {
  return locale.replace(/-([a-zA-Z])/g, (_, c: string) => c.toUpperCase());
}

/** Produce a TS locale file for `locale`. */
export function buildLocaleFile(locale: string): string {
  const meta = LOCALES[locale]!;
  const entries = loadStrings(locale);
  const id = toIdentifier(locale);

  // Collect only strings that differ from the English source (true translations).
  const overrides: Record<string, string> = {};
  for (const key of WEB_COMPONENT_KEYS) {
    const translated = entries[key];
    if (translated !== undefined && translated !== englishSources[key]) {
      overrides[key] = translated;
    }
  }

  const hasOverrides = Object.keys(overrides).length > 0;
  const stringsArg = hasOverrides
    ? `, {\n${Object.entries(overrides)
        .map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
        .join("\n")}\n  }`
    : "";

  return `// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** ${meta.label} locale bundle. */
export const ${id}: LocaleBundle = defineBundle({
  locale: ${JSON.stringify(locale)},
  dir: ${JSON.stringify(meta.dir)},
  label: ${JSON.stringify(meta.label)},
  strings: makeStrings(${JSON.stringify(locale)}${stringsArg}),
});
`;
}

const locales = Object.keys(LOCALES);
for (const locale of locales) {
  const content = buildLocaleFile(locale);
  const id = toIdentifier(locale);
  writeFileSync(join(localesDir, `${locale}.ts`), content);
  console.log(`  ${locale} → src/locales/${locale}.ts (${id})`);
}

console.log(`\n✓ i18n build-bundles: wrote ${locales.length} locale files`);
