// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Danish (Dansk) locale bundle. */
export const da: LocaleBundle = defineBundle({
  locale: "da",
  dir: "ltr",
  label: "Danish (Dansk)",
  strings: makeStrings("da", {
    prevMonth: "Forrige måned",
    nextMonth: "Næste måned",
    dateLabel: "Dato",
    datePlaceholder: "åååå-mm-dd",
    openCalendar: "Åbn kalender",
    timeLabel: "Tid",
    back: "Tilbage",
  }),
});
