// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Greek (Ελληνικά) locale bundle. */
export const el: LocaleBundle = defineBundle({
  locale: "el",
  dir: "ltr",
  label: "Greek (Ελληνικά)",
  strings: makeStrings("el", {
    prevMonth: "Προηγούμενος μήνας",
    nextMonth: "Επόμενος μήνας",
    dateLabel: "Ημερομηνία",
    openCalendar: "Άνοιγμα ημερολογίου",
    timeLabel: "Ώρα",
    back: "Πίσω",
  }),
});
