// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Persian / Farsi (فارسی) locale bundle. */
export const fa: LocaleBundle = defineBundle({
  locale: "fa",
  dir: "rtl",
  label: "Persian / Farsi (فارسی)",
  strings: makeStrings("fa", {
    prevMonth: "ماه قبل",
    nextMonth: "ماه بعد",
    dateLabel: "تاریخ",
    openCalendar: "باز کردن تقویم",
    timeLabel: "زمان",
    back: "بازگشت",
  }),
});
