// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Indonesian locale bundle. */
export const id: LocaleBundle = defineBundle({
  locale: "id",
  dir: "ltr",
  label: "Indonesian",
  strings: makeStrings("id", {
    prevMonth: "Bulan sebelumnya",
    nextMonth: "Bulan berikutnya",
    dateLabel: "Tanggal",
    openCalendar: "Buka kalender",
    timeLabel: "Waktu",
    back: "Kembali",
  }),
});
