// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Italian (Italiano) locale bundle. */
export const it: LocaleBundle = defineBundle({
  locale: "it",
  dir: "ltr",
  label: "Italian (Italiano)",
  strings: makeStrings("it", {
    prevMonth: "Mese precedente",
    nextMonth: "Mese successivo",
    dateLabel: "Data",
    datePlaceholder: "aaaa-mm-gg",
    openCalendar: "Apri calendario",
    timeLabel: "Ora",
    back: "Indietro",
  }),
});
