// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Japanese (日本語) locale bundle. */
export const ja: LocaleBundle = defineBundle({
  locale: "ja",
  dir: "ltr",
  label: "Japanese (日本語)",
  strings: makeStrings("ja", {
    prevMonth: "前の月",
    nextMonth: "次の月",
    dateLabel: "日付",
    openCalendar: "カレンダーを開く",
    timeLabel: "時刻",
    back: "戻る",
  }),
});
