// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Maori (Reo Māori) locale bundle. */
export const mi: LocaleBundle = defineBundle({
  locale: "mi",
  dir: "ltr",
  label: "Maori (Reo Māori)",
  strings: makeStrings("mi", {
    prevMonth: "Marama o mua",
    nextMonth: "Marama o muri",
    dateLabel: "Rā",
    openCalendar: "Whakatuwhera maramataka",
    timeLabel: "Wā",
    back: "Hoki",
  }),
});
