// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Dutch (Nederlands) locale bundle. */
export const nl: LocaleBundle = defineBundle({
  locale: "nl",
  dir: "ltr",
  label: "Dutch (Nederlands)",
  strings: makeStrings("nl", {
    prevMonth: "Vorige maand",
    nextMonth: "Volgende maand",
    dateLabel: "Datum",
    openCalendar: "Open kalender",
    timeLabel: "Tijd",
    back: "Terug",
  }),
});
