// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Polish (Polski) locale bundle. */
export const pl: LocaleBundle = defineBundle({
  locale: "pl",
  dir: "ltr",
  label: "Polish (Polski)",
  strings: makeStrings("pl", {
    prevMonth: "Poprzedni miesiąc",
    nextMonth: "Następny miesiąc",
    dateLabel: "Data",
    datePlaceholder: "rrrr-mm-dd",
    openCalendar: "Otwórz kalendarz",
    timeLabel: "Czas",
    back: "Wstecz",
  }),
});
