// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Portuguese Brazil (Português do Brasil) locale bundle. */
export const ptBR: LocaleBundle = defineBundle({
  locale: "pt-BR",
  dir: "ltr",
  label: "Portuguese Brazil (Português do Brasil)",
  strings: makeStrings("pt-BR", {
    prevMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    dateLabel: "Data",
    datePlaceholder: "aaaa-mm-dd",
    openCalendar: "Abrir calendário",
    timeLabel: "Hora",
    back: "Voltar",
  }),
});
