// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Northern Sami locale bundle. */
export const se: LocaleBundle = defineBundle({
  locale: "se",
  dir: "ltr",
  label: "Northern Sami",
  strings: makeStrings("se", {
    prevMonth: "Föregående månad",
    nextMonth: "Nästa månad",
    dateLabel: "Datum",
    datePlaceholder: "åååå-mm-dd",
    openCalendar: "Öppna kalender",
    timeLabel: "Tid",
    back: "Tillbaka",
  }),
});
