// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Thai (ไทย) locale bundle. */
export const th: LocaleBundle = defineBundle({
  locale: "th",
  dir: "ltr",
  label: "Thai (ไทย)",
  strings: makeStrings("th", {
    prevMonth: "เดือนก่อนหน้า",
    nextMonth: "เดือนถัดไป",
    dateLabel: "วันที่",
    openCalendar: "เปิดปฏิทิน",
    timeLabel: "เวลา",
    back: "ย้อนกลับ",
  }),
});
