// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Ukrainian (Українська) locale bundle. */
export const uk: LocaleBundle = defineBundle({
  locale: "uk",
  dir: "ltr",
  label: "Ukrainian (Українська)",
  strings: makeStrings("uk", {
    prevMonth: "Попередній місяць",
    nextMonth: "Наступний місяць",
    dateLabel: "Дата",
    datePlaceholder: "рррр-mm-dd",
    openCalendar: "Відкрити календар",
    timeLabel: "Час",
    back: "Назад",
  }),
});
