// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Vietnamese locale bundle. */
export const vi: LocaleBundle = defineBundle({
  locale: "vi",
  dir: "ltr",
  label: "Vietnamese",
  strings: makeStrings("vi", {
    prevMonth: "Tháng trước",
    nextMonth: "Tháng sau",
    dateLabel: "Ngày",
    openCalendar: "Mở lịch",
    timeLabel: "Thời gian",
    back: "Quay lại",
  }),
});
