// Generated by scripts/build-bundles.ts — do not edit by hand.
import type { LocaleBundle } from "../locale-bundle.ts";
import { defineBundle, makeStrings } from "../locale-bundle.ts";

/** Traditional Chinese (繁體中文) locale bundle. */
export const zhHant: LocaleBundle = defineBundle({
  locale: "zh-Hant",
  dir: "ltr",
  label: "Traditional Chinese (繁體中文)",
  strings: makeStrings("zh-Hant", {
    prevMonth: "上個月",
    nextMonth: "下個月",
    dateLabel: "日期",
    openCalendar: "開啟日曆",
    timeLabel: "時間",
    back: "返回",
  }),
});
