// Shared by plugins/pantoken/*/scripts/component-styles.ts — compile CSS source files to a TS constants module.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

function findCssFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) results.push(...findCssFiles(join(dir, entry.name)));
    else if (entry.name.endsWith(".css")) results.push(join(dir, entry.name));
  }
  return results.sort();
}

function toIdentifier(file: string, sourceDir: string): string {
  const segments = relative(sourceDir, file)
    .replace(/\.css$/u, "")
    .split(/[/\\]/u)
    .map((s) => s.replace(/-([a-z0-9])/gu, (_, c: string) => c.toUpperCase()));
  // collapse a trailing segment that duplicates its predecessor
  if (segments.length > 1 && segments.at(-1) === segments.at(-2)) segments.pop();
  return segments.map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1))).join("");
}

/**
 * Compile all `.css` files under `sourceDir` into a TS constants module at `outFile`.
 * Each file becomes `export const <camelCaseIdentifier>: string = "<css content>";`.
 * Trailing duplicate path segments are collapsed (`card/card.css` → `card`).
 * @param sourceDir - Root directory to scan recursively for `.css` files.
 * @param outFile - Absolute path to the generated `.ts` output file.
 * @param label - Short name used in the success log line.
 */
export function compileCssToTs(sourceDir: string, outFile: string, label: string): void {
  const outDir = resolve(outFile, "..");
  const files = findCssFiles(sourceDir);
  const entries = files.map((file) => {
    const css = readFileSync(file, "utf8");
    return `export const ${toIdentifier(file, sourceDir)}: string = ${JSON.stringify(css)};`;
  });
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    outFile,
    `// AUTO-GENERATED by scripts/component-styles.ts — do not edit.\n${entries.join("\n")}\n`,
  );
  console.log(
    `✓ ${label}: wrote ${outFile.replace(resolve(outFile, "../../../.."), "")} (${entries.length} record(s))`,
  );
}
