/**
 * Emit the pantoken IR as SCSS variables. Values are resolved to concrete, single-mode values so
 * the output is a self-contained SCSS token file (`$instui-color-brand: #0374b5;`). Icon tokens are
 * skipped — they belong in CSS, not SCSS variables.
 *
 * @module
 */
import { resolveTokens } from "@pantoken/utils";
import type { Mode } from "@pantoken/utils";
import type { Token } from "@pantoken/model";

export type { Mode } from "@pantoken/utils";

/** Options for {@link toScss}. */
export interface ToScssOptions {
  /** Which colour mode to resolve (default `"light"`). */
  mode?: Mode;
}

/**
 * Emit SCSS variables for a token IR.
 *
 * @param tokens - The IR (e.g. from `@pantoken/tokens`).
 * @param options - {@link ToScssOptions}.
 * @returns The SCSS source string.
 *
 * @example Emit the default (light) variables
 * ```ts
 * import { toScss } from "@pantoken/scss";
 * import { tokens } from "@pantoken/tokens";
 *
 * toScss(tokens); // "$instui-color-brand: #0374b5;\n…"
 * ```
 *
 * @example Resolve the dark mode of another theme
 * ```ts
 * import { toScss } from "@pantoken/scss";
 * import { byTheme } from "@pantoken/tokens";
 *
 * toScss(byTheme("canvas"), { mode: "dark" });
 * ```
 */
export function toScss(tokens: readonly Token[], options: ToScssOptions = {}): string {
  const resolved = resolveTokens(tokens, { mode: options.mode ?? "light" });
  const lines = ["// DO NOT EDIT — generated by @pantoken/scss", ""];
  for (const token of tokens) {
    if (token.meta?.kind === "icon") continue;
    lines.push(`$${token.name.replace(/^--/, "")}: ${resolved.get(token.name) ?? token.value};`);
  }
  return `${lines.join("\n")}\n`;
}
