/**
 * Inline the scaffold template files into a generated TS module (so the package ships them as
 * string constants — no runtime dependency on the raw `templates/` files).
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { generateMessageBundles, loadConfig, parsePo, readCatalog } from "@pantoken/i18n-engine";
import { renderWrapperContainer, wrapperRootClassName } from "@pantoken/scaffold-base";
import type { CompiledScaffoldMetadata, ScaffoldMetadata } from "../src/scaffold-metadata.ts";
import { flattenSource, type SourceEntry } from "./i18n-sources.ts";
import { LOCALES } from "./lib/locales.ts";

const root = resolve(import.meta.dirname, "..");
const repoRoot = resolve(root, "../..");
const templatesRoot = join(root, "templates");
// Read the shared cssdoc template from scaffold-base (JSONC with comments)
const scaffoldBaseTemplates = resolve(root, "../scaffold-base/templates");
const cssdocJsonc = readFileSync(join(scaffoldBaseTemplates, "cssdoc.jsonc"), "utf8");
// Parse JSONC: strip line comments outside of string literals (block comments are not used in
// this repo's templates). Matching whole strings first keeps a `//` inside a string untouched.
const stripJsoncComments = (input: string): string =>
  input.replace(/"(?:[^"\\]|\\.)*"|\/\/[^\n]*/g, (match) => (match.startsWith("//") ? "" : match));
const sharedCssdocTemplate = JSON.stringify(JSON.parse(stripJsoncComments(cssdocJsonc)), null, 2);

// Every template's entry markup is patterned off `@pantoken/plugin-layouts`'s `wrapper` app-shell
// layout via these tokens, so editing that layout's cssdoc regenerates every platform's markup.
const rootClassName = wrapperRootClassName();
function substituteWrapperTokens(content: string): string {
  return content
    .replaceAll("{{wrapperRootClass}}", rootClassName)
    .replace(/\{\{wrapperContainer:(html|jsx):(\d+)\}\}/g, (_match, format, depth) =>
      renderWrapperContainer(format as "html" | "jsx", Number(depth)).replace(/^\s+/, ""),
    );
}

const scaffolds: Record<string, Record<string, string>> = {};
for (const platform of readdirSync(templatesRoot, { withFileTypes: true })) {
  if (!platform.isDirectory()) continue;
  const platformDir = join(templatesRoot, platform.name);
  const files: Record<string, string> = {};
  for (const entry of readdirSync(platformDir, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const abs = join(entry.parentPath, entry.name);
    // .tmpl-suffixed template files (.ts/.tsx) are stripped back to their real extension here, so
    // they're never picked up by this package's own TypeScript tooling as real source.
    const relPath = relative(platformDir, abs).split("\\").join("/");
    // scaffold.json is CLI-facing metadata (next steps/notes/caveats), not project source.
    // src/i18n.json is the English source of truth for src/strings.ts (synthesized below), also
    // not shipped as project source.
    if (relPath === "scaffold.json" || relPath === "src/i18n.json") continue;
    files[relPath.endsWith(".tmpl") ? relPath.slice(0, -".tmpl".length) : relPath] =
      substituteWrapperTokens(readFileSync(abs, "utf8"));
  }
  // Every scaffold gets the same cssdoc schema file from one shared template source.
  files["cssdoc.json"] = sharedCssdocTemplate;
  // Platforms with their own src/i18n.json get a generated src/strings.ts of English UI strings,
  // resolved at runtime by the platform's own {{key}} substitution (see main.ts.tmpl's render()).
  const templateI18nPath = join(platformDir, "src/i18n.json");
  if (existsSync(templateI18nPath)) {
    const strings = flattenSource(
      JSON.parse(readFileSync(templateI18nPath, "utf8")) as Record<string, SourceEntry>,
    );
    files["src/strings.ts"] =
      `// GENERATED by scripts/generate.ts — do not edit by hand.\n/** English UI strings, resolved at runtime by the platform's \`{{key}}\` substitution. */\nexport const STRINGS: Record<string, string> = ${JSON.stringify(strings, null, 2)};\n`;
  }
  scaffolds[platform.name] = files;
}

const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "scaffolds.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const SCAFFOLDS: Record<string, Record<string, string>> = ${JSON.stringify(scaffolds, null, 2)};\n`,
);
console.log(`✓ inlined scaffold templates for ${Object.keys(scaffolds).length} platforms`);

// Per-locale overrides layered over SCAFFOLDS at scaffold time. Read the committed PO catalogs
// directly so a clean checkout produces the same package without a separate render step.
const overlays: Record<string, Record<string, Record<string, string>>> = {};
for (const locale of Object.keys(LOCALES)) {
  const catalog = parsePo(readCatalog(join(repoRoot, "l10n", locale, "scaffold.readme.po")) ?? "");
  const translations = new Map(
    catalog
      .filter((entry) => !entry.obsolete && !entry.fuzzy && entry.msgstr !== "")
      .map((entry) => [entry.msgid, entry.msgstr]),
  );
  const byPlatform: Record<string, Record<string, string>> = {};
  for (const [platform, files] of Object.entries(scaffolds)) {
    const localized = translations.get(files["README.md"]);
    if (!localized) continue;
    if (localized === files["README.md"]) continue;
    byPlatform[platform] = { "README.md": localized };
  }
  if (Object.keys(byPlatform).length > 0) overlays[locale] = byPlatform;
}
writeFileSync(
  join(outDir, "scaffold-overlays.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\n/** Locale \u2192 platform \u2192 file overrides layered over \`SCAFFOLDS\`; English files are omitted. */\nexport const SCAFFOLD_OVERLAYS: Record<string, Record<string, Record<string, string>>> = ${JSON.stringify(overlays, null, 2)};\n`,
);
console.log(`✓ inlined localized scaffold files for ${Object.keys(overlays).length} locale(s)`);

// Compile each template's optional scaffold.json (nextSteps/notes/caveats) into i18n key names —
// the resolved text is looked up from the locale bundle at print-time, not baked in here.
const scaffoldMetadata: Record<string, CompiledScaffoldMetadata> = {};
for (const platform of readdirSync(templatesRoot, { withFileTypes: true })) {
  if (!platform.isDirectory()) continue;
  const metaPath = join(templatesRoot, platform.name, "scaffold.json");
  if (!existsSync(metaPath)) continue;

  const meta = JSON.parse(readFileSync(metaPath, "utf8")) as ScaffoldMetadata;
  const prefix = platform.name;
  scaffoldMetadata[platform.name] = {
    nextStepsKeys: (meta.nextSteps ?? []).map((_, i) => `${prefix}.nextSteps.${i}`),
    ...(meta.notes ? { notesKey: `${prefix}.notes` } : {}),
    ...(meta.caveats ? { caveatsKey: `${prefix}.caveats` } : {}),
  };
}
writeFileSync(
  join(outDir, "scaffold-metadata.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const SCAFFOLD_METADATA: Record<string, { nextStepsKeys: string[]; notesKey?: string; caveatsKey?: string }> = ${JSON.stringify(scaffoldMetadata, null, 2)};\n`,
);
console.log(
  `✓ compiled scaffold.json metadata for ${Object.keys(scaffoldMetadata).length} platform(s)`,
);

generateMessageBundles(
  loadConfig(resolve(root, "../../i18n.config.json")),
  resolve(root, "../.."),
  "cli.scaffold",
  Object.keys(LOCALES),
  outDir,
);

// Runtime copy of the locale registry: `src/` must stay Node-free, so it can't read `scripts/lib`.
writeFileSync(
  join(outDir, "locale-registry.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\n/** Text direction per supported BCP47 tag; its keys are the tags \`--lang\` accepts. */\nexport const LOCALE_DIRS: Record<string, "ltr" | "rtl"> = ${JSON.stringify(
    Object.fromEntries(Object.entries(LOCALES).map(([tag, info]) => [tag, info.dir])),
    null,
    2,
  )};\n`,
);
console.log(`✓ emitted locale registry for ${Object.keys(LOCALES).length} locales`);
