/**
 * Inline the scaffold template files into a generated TS module (so the package ships them as
 * string constants — no runtime dependency on the raw `templates/` files).
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { renderWrapperContainer, wrapperRootClassName } from "@pantoken/scaffold-base";

const root = resolve(import.meta.dirname, "..");
const templatesRoot = join(root, "templates");
// Read the shared cssdoc template from scaffold-base (JSONC with comments)
const scaffoldBaseTemplates = resolve(root, "../scaffold-base/templates");
const cssdocJsonc = readFileSync(join(scaffoldBaseTemplates, "cssdoc.jsonc"), "utf8");
// Parse JSONC: strip line comments outside of string literals (block comments are not used in
// this repo's templates). Matching whole strings first keeps a `//` inside a string untouched.
const stripJsoncComments = (input: string): string =>
  input.replace(/"(?:[^"\\]|\\.)*"|\/\/[^\n]*/g, (match) => (match.startsWith("//") ? "" : match));
const sharedCssdocTemplate = JSON.stringify(JSON.parse(stripJsoncComments(cssdocJsonc)), null, 2);

// Every template's entry markup is patterned off `@pantoken/plugin-layouts`'s `wrapper` app-shell
// layout via these tokens, so editing that layout's cssdoc regenerates every platform's markup.
const rootClassName = wrapperRootClassName();
function substituteWrapperTokens(content: string): string {
  return content
    .replaceAll("{{wrapperRootClass}}", rootClassName)
    .replace(/\{\{wrapperContainer:(html|jsx):(\d+)\}\}/g, (_match, format, depth) =>
      renderWrapperContainer(format as "html" | "jsx", Number(depth)).replace(/^\s+/, ""),
    );
}

const scaffolds: Record<string, Record<string, string>> = {};
for (const platform of readdirSync(templatesRoot, { withFileTypes: true })) {
  if (!platform.isDirectory()) continue;
  const platformDir = join(templatesRoot, platform.name);
  const files: Record<string, string> = {};
  for (const entry of readdirSync(platformDir, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const abs = join(entry.parentPath, entry.name);
    // .tmpl-suffixed template files (.ts/.tsx) are stripped back to their real extension here, so
    // they're never picked up by this package's own TypeScript tooling as real source.
    const relPath = relative(platformDir, abs).split("\\").join("/");
    files[relPath.endsWith(".tmpl") ? relPath.slice(0, -".tmpl".length) : relPath] =
      substituteWrapperTokens(readFileSync(abs, "utf8"));
  }
  // Every scaffold gets the same cssdoc schema file from one shared template source.
  files["cssdoc.json"] = sharedCssdocTemplate;
  scaffolds[platform.name] = files;
}

const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "scaffolds.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const SCAFFOLDS: Record<string, Record<string, string>> = ${JSON.stringify(scaffolds, null, 2)};\n`,
);
console.log(`✓ inlined scaffold templates for ${Object.keys(scaffolds).length} platforms`);

// Generate locale bundles from i18n-cache
const i18nCacheDir = join(root, "i18n-cache");
const localesDir = join(outDir, "locales");
mkdirSync(localesDir, { recursive: true });

const localeMap: Record<string, string> = {};
try {
  const cacheFiles = readdirSync(i18nCacheDir);
  for (const file of cacheFiles) {
    if (!file.endsWith(".json")) continue;
    const locale = file.slice(0, -".json".length);
    const cachePath = join(i18nCacheDir, file);
    const bundle = JSON.parse(readFileSync(cachePath, "utf8"));

    // Generate a TypeScript file for this locale
    const tsContent = `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const LOCALE_${locale.toUpperCase()} = ${JSON.stringify(
      bundle,
      null,
      2,
    )} as const;\n`;
    writeFileSync(join(localesDir, `${locale}.ts`), tsContent);
    localeMap[locale] = `LOCALE_${locale.toUpperCase()}`;
  }
} catch {
  // i18n-cache directory doesn't exist yet, that's okay
}

// Generate the index that exports all locales
const indexContent = `// GENERATED by scripts/generate.ts — do not edit by hand.
${Object.entries(localeMap)
  .map(([locale, varName]) => `import { ${varName} } from "./${locale}.js";`)
  .join("\n")}

export const LOCALES: Record<string, Record<string, string>> = {
${Object.entries(localeMap)
  .map(([locale, varName]) => `  ${locale}: ${varName},`)
  .join("\n")}
};
`;
writeFileSync(join(localesDir, "index.ts"), indexContent);
if (Object.keys(localeMap).length > 0) {
  console.log(`✓ generated locale bundles for: ${Object.keys(localeMap).join(", ")}`);
}
