/**
 * Inline the scaffold template files into a generated TS module (so the package ships them as
 * string constants — no runtime dependency on the raw `templates/` files).
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { THEME_CSS, THEME_JS } from "@pantoken/canvas-theme-editor";
import { renderWrapperContainer, wrapperRootClassName } from "@pantoken/scaffold-base";
import { generateLocaleBundles } from "@pantoken/translation-adapters";

// canvas-theme-editor's theme.css/theme.js are owned by @pantoken/canvas-theme-editor (so they can
// be published/consumed standalone too) rather than duplicated as on-disk template files here.
const THEME_ASSET_OVERRIDES: Record<string, Record<string, string>> = {
  "canvas-theme-editor": { "theme.css": THEME_CSS, "theme.js": THEME_JS },
};

const root = resolve(import.meta.dirname, "..");
const templatesRoot = join(root, "templates");
// Read the shared cssdoc template from scaffold-base (JSONC with comments)
const scaffoldBaseTemplates = resolve(root, "../scaffold-base/templates");
const cssdocJsonc = readFileSync(join(scaffoldBaseTemplates, "cssdoc.jsonc"), "utf8");
// Parse JSONC: strip line comments outside of string literals (block comments are not used in
// this repo's templates). Matching whole strings first keeps a `//` inside a string untouched.
const stripJsoncComments = (input: string): string =>
  input.replace(/"(?:[^"\\]|\\.)*"|\/\/[^\n]*/g, (match) => (match.startsWith("//") ? "" : match));
const sharedCssdocTemplate = JSON.stringify(JSON.parse(stripJsoncComments(cssdocJsonc)), null, 2);

// Every template's entry markup is patterned off `@pantoken/plugin-layouts`'s `wrapper` app-shell
// layout via these tokens, so editing that layout's cssdoc regenerates every platform's markup.
const rootClassName = wrapperRootClassName();
function substituteWrapperTokens(content: string): string {
  return content
    .replaceAll("{{wrapperRootClass}}", rootClassName)
    .replace(/\{\{wrapperContainer:(html|jsx):(\d+)\}\}/g, (_match, format, depth) =>
      renderWrapperContainer(format as "html" | "jsx", Number(depth)).replace(/^\s+/, ""),
    );
}

const scaffolds: Record<string, Record<string, string>> = {};
for (const platform of readdirSync(templatesRoot, { withFileTypes: true })) {
  if (!platform.isDirectory()) continue;
  const platformDir = join(templatesRoot, platform.name);
  const files: Record<string, string> = {};
  for (const entry of readdirSync(platformDir, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const abs = join(entry.parentPath, entry.name);
    // .tmpl-suffixed template files (.ts/.tsx) are stripped back to their real extension here, so
    // they're never picked up by this package's own TypeScript tooling as real source.
    const relPath = relative(platformDir, abs).split("\\").join("/");
    // scaffold.json is CLI-facing metadata (next steps/notes/caveats), not project source.
    if (relPath === "scaffold.json") continue;
    files[relPath.endsWith(".tmpl") ? relPath.slice(0, -".tmpl".length) : relPath] =
      substituteWrapperTokens(readFileSync(abs, "utf8"));
  }
  // Every scaffold gets the same cssdoc schema file from one shared template source.
  files["cssdoc.json"] = sharedCssdocTemplate;
  Object.assign(files, THEME_ASSET_OVERRIDES[platform.name]);
  scaffolds[platform.name] = files;
}

const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "scaffolds.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const SCAFFOLDS: Record<string, Record<string, string>> = ${JSON.stringify(scaffolds, null, 2)};\n`,
);
console.log(`✓ inlined scaffold templates for ${Object.keys(scaffolds).length} platforms`);

// Compile each template's optional scaffold.json (nextSteps/notes/caveats) into i18n key names —
// the resolved text is looked up from the locale bundle at print-time, not baked in here.
const scaffoldMetadata: Record<
  string,
  { nextStepsKeys: string[]; notesKey?: string; caveatsKey?: string }
> = {};
for (const platform of readdirSync(templatesRoot, { withFileTypes: true })) {
  if (!platform.isDirectory()) continue;
  const metaPath = join(templatesRoot, platform.name, "scaffold.json");
  if (!existsSync(metaPath)) continue;

  const meta = JSON.parse(readFileSync(metaPath, "utf8")) as {
    nextSteps?: string[];
    notes?: string;
    caveats?: string;
  };
  const prefix = `scaffold.${platform.name}`;
  scaffoldMetadata[platform.name] = {
    nextStepsKeys: (meta.nextSteps ?? []).map((_, i) => `${prefix}.nextSteps.${i}`),
    ...(meta.notes ? { notesKey: `${prefix}.notes` } : {}),
    ...(meta.caveats ? { caveatsKey: `${prefix}.caveats` } : {}),
  };
}
writeFileSync(
  join(outDir, "scaffold-metadata.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const SCAFFOLD_METADATA: Record<string, { nextStepsKeys: string[]; notesKey?: string; caveatsKey?: string }> = ${JSON.stringify(scaffoldMetadata, null, 2)};\n`,
);
console.log(
  `✓ compiled scaffold.json metadata for ${Object.keys(scaffoldMetadata).length} platform(s)`,
);

generateLocaleBundles(root, outDir);
