/**
 * Live HMR dev preview of a materialized scaffold. Materializes `<platform>` into an untracked
 * `.dev/<platform>` directory, links its `@pantoken/*` runtime deps to local workspace source, and
 * runs its own Vite dev server so a browser gets real HMR — both for edits to the scaffold's own
 * source and for edits to the linked-in workspace packages it depends on.
 *
 * Two independent watch/rebuild layers:
 *  - Authoring source (`templates/<platform>`, `src/`, `scaffold-base/{src,templates}`): a change
 *    here re-materializes the files in `.dev/<platform>`; the already-running Vite dev server picks
 *    up the rewrite via its own file watcher.
 *  - Linked `@pantoken/*` runtime deps: handled entirely by `@pantoken/vite-workspace-orchestrator`,
 *    wired into a synthesized `vite.config.dev.ts` (see {@link writeDevViteConfig}) — this script
 *    doesn't watch or rebuild those itself.
 *
 * Usage: `vp run scaffold:dev <platform>` (root) or
 * `vp run @pantoken/scaffold#scaffold:dev <platform>`. `next` isn't supported yet — `next dev`
 * isn't Vite, so the orchestrator plugin has nowhere to attach.
 */
import { execFileSync, spawn, type ChildProcess } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, watch as watchFs, writeFileSync } from "node:fs";
import type { FSWatcher } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveScaffoldPlatform } from "../src/index.ts";

const SCAFFOLD_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REPO_ROOT = resolve(SCAFFOLD_DIR, "../..");
const REMATERIALIZE_DEBOUNCE_MS = 200;

/** Maps a scaffolded `@pantoken/*` dependency name to its monorepo package directory. */
const PACKAGE_DIRS: Record<string, string> = {
  "@pantoken/css": "formats/css",
  "@pantoken/components": "formats/components",
  "@pantoken/plugin-layouts": "plugins/pantoken/layouts",
  "@pantoken/react": "renderers/react",
  "@pantoken/vue": "renderers/vue",
  "@pantoken/svelte": "renderers/svelte",
  "@pantoken/web-components": "renderers/web-components",
  "@pantoken/angular": "renderers/angular",
  "@pantoken/canvas-theme-editor": "platforms/canvas-theme-editor",
  "@pantoken/cdn": "packages/cdn",
  "@pantoken/vite-workspace-orchestrator": "plugins/vite/workspace-orchestrator",
};

function readMaterializedPackageJson(devDir: string): {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
} {
  return JSON.parse(readFileSync(join(devDir, "package.json"), "utf8")) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
}

/** Linked `@pantoken/*` deps a materialized platform declares (present in `PACKAGE_DIRS`). */
function linkedDeps(devDir: string): string[] {
  const pkg = readMaterializedPackageJson(devDir);
  const all = { ...pkg.dependencies, ...pkg.devDependencies };
  return Object.keys(all).filter((name) => name in PACKAGE_DIRS);
}

/**
 * Writes `vite.config.dev.ts` — a synthesized config (not part of the real scaffold output) that
 * layers `workspaceOrchestrator()` on top of the scaffolded `vite.config.ts`, one upstream node per
 * linked `@pantoken/*` dependency, then adds the orchestrator itself as a devDependency so
 * `firstTimeSetup` installs and links it too. Overwritten on every materialize — cheap, and
 * regenerating it fresh each time keeps it correct without merge logic.
 */
function writeDevViteConfig(devDir: string): void {
  const pkgJsonPath = join(devDir, "package.json");
  const pkg = readMaterializedPackageJson(devDir) as Record<string, unknown> & {
    devDependencies?: Record<string, string>;
  };
  const deps = linkedDeps(devDir);
  if (deps.length === 0) return;

  pkg.devDependencies = {
    ...pkg.devDependencies,
    "@pantoken/vite-workspace-orchestrator": "latest",
  };
  writeFileSync(pkgJsonPath, `${JSON.stringify(pkg, null, 2)}\n`);

  const nodes = deps.map((name) => {
    const dir = join(REPO_ROOT, PACKAGE_DIRS[name]!);
    return { name, dir };
  });

  const nodesCode = nodes
    .map(
      (n) =>
        `    { name: ${JSON.stringify(n.name)}, dir: ${JSON.stringify(n.dir)}, watchPaths: [${JSON.stringify(join(n.dir, "src"))}], build: ["vp", "run", ${JSON.stringify(`${n.name}#build`)}], dependents: [] }`,
    )
    .join(",\n");
  const outputPaths = nodes
    .map(
      (n) => `${JSON.stringify(join(n.dir, "dist"))}, ${JSON.stringify(join(n.dir, "generated"))}`,
    )
    .join(", ");

  const content = `// Auto-generated by \`scaffold:dev\` — links this preview's @pantoken/* deps to local
// monorepo source so editing them hot-reloads here too. Not part of the real scaffold output.
import { defineConfig, mergeConfig } from "vite";
import { workspaceOrchestrator } from "@pantoken/vite-workspace-orchestrator";
import base from "./vite.config.ts";

export default defineConfig(
  mergeConfig(base, {
    plugins: [
      workspaceOrchestrator({
        upstream: [
${nodesCode}
        ],
        outputWatchPaths: [${outputPaths}],
      }),
    ],
  }),
);
`;
  writeFileSync(join(devDir, "vite.config.dev.ts"), content);
}

/** Reruns `scan-presets.ts` + `generate.ts` so `generated/*` reflects the latest authoring source. */
function regenerate(): void {
  execFileSync("node", ["scripts/scan-presets.ts"], { cwd: SCAFFOLD_DIR, stdio: "inherit" });
  execFileSync("node", ["scripts/generate.ts"], { cwd: SCAFFOLD_DIR, stdio: "inherit" });
}

/** Regenerates, then re-materializes `platform` into `devDir` (overwrites every file). */
function materialize(platform: string, devDir: string): void {
  regenerate();
  execFileSync("node", [join(SCAFFOLD_DIR, "scripts/materialize-once.ts"), platform, devDir], {
    stdio: "inherit",
  });
  writeDevViteConfig(devDir);
}

/** `vp install` + `vp link` for every linked `@pantoken/*` dep — once, before the first dev-server start. */
function firstTimeSetup(devDir: string): void {
  // `--ignore-scripts`: pnpm's default "ignored build scripts need approval" gate makes
  // `vp install` exit non-zero for unrelated native-build subdeps (e.g. core-js, ttf2woff2) pulled
  // in transitively — this is a throwaway preview install, not something that needs those scripts.
  execFileSync("vp", ["install", "--ignore-scripts"], { cwd: devDir, stdio: "inherit" });
  for (const name of linkedDeps(devDir)) {
    execFileSync("vp", ["link", join(REPO_ROOT, PACKAGE_DIRS[name]!)], {
      cwd: devDir,
      stdio: "inherit",
    });
  }
}

function startDevServer(devDir: string): ChildProcess {
  const viteBin = join(devDir, "node_modules", ".bin", "vite");
  const hasDevConfig = existsSync(join(devDir, "vite.config.dev.ts"));
  return spawn(viteBin, hasDevConfig ? ["--config", "vite.config.dev.ts"] : [], {
    cwd: devDir,
    stdio: "inherit",
  });
}

/** Reads + validates the platform CLI arg; exits the process for a missing/unsupported one. */
function resolvePlatformArg(): string {
  const platformArg = process.argv[2];
  if (!platformArg) {
    console.error("Usage: vp run scaffold:dev <platform>");
    process.exit(1);
  }
  if (platformArg === "next") {
    console.error("scaffold:dev doesn't support \"next\" yet — next dev isn't Vite-based.");
    process.exit(1);
  }
  return resolveScaffoldPlatform(platformArg);
}

/** Creates `.dev/<platform>` and isolates it from the monorepo's own pnpm workspace. */
function prepareDevDir(platform: string): string {
  const devDir = join(SCAFFOLD_DIR, ".dev", platform);
  mkdirSync(devDir, { recursive: true });
  // .dev/<platform> sits inside the monorepo's own directory tree, so without its own
  // pnpm-workspace.yaml, pnpm walks up and finds the REAL one — `vp install` then treats it as
  // part of the 90-package monorepo workspace instead of an isolated project. An empty one here
  // stops that upward search. `blockExoticSubdeps` also has to live here (not .npmrc — pnpm only
  // reads auth/registry settings from .npmrc): the published `@pantoken/pantoken` meta package
  // devDependency every scaffold ships pulls in a git-hosted transitive dep pnpm's default policy
  // rejects as a subdependency.
  writeFileSync(join(devDir, "pnpm-workspace.yaml"), "packages: []\nblockExoticSubdeps: false\n");
  return devDir;
}

/** Watches Layer-A authoring source for `platform`, debounced re-materializing into `devDir`. */
function watchAuthoringSource(platform: string, devDir: string): FSWatcher[] {
  const watchTargets = [
    join(SCAFFOLD_DIR, "templates", platform),
    join(SCAFFOLD_DIR, "src"),
    resolve(SCAFFOLD_DIR, "../scaffold-base/src"),
    resolve(SCAFFOLD_DIR, "../scaffold-base/templates"),
  ];
  let pending: NodeJS.Timeout | undefined;
  const scheduleRematerialize = (): void => {
    if (pending) clearTimeout(pending);
    pending = setTimeout(() => {
      try {
        materialize(platform, devDir);
      } catch (err) {
        console.error("[scaffold:dev] rematerialize failed:", err);
      }
    }, REMATERIALIZE_DEBOUNCE_MS);
  };
  return watchTargets
    .filter((target) => existsSync(target))
    .map((target) => watchFs(target, { recursive: true }, scheduleRematerialize));
}

/** Closes `watchers` and kills `devServer` on SIGINT/SIGTERM or the dev server's own exit. */
function wireShutdown(watchers: FSWatcher[], devServer: ChildProcess): void {
  const shutdown = (): void => {
    for (const watcher of watchers) watcher.close();
    devServer.kill();
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
  devServer.on("exit", (code) => {
    for (const watcher of watchers) watcher.close();
    process.exit(code ?? 0);
  });
}

function main(): void {
  const platform = resolvePlatformArg();
  const devDir = prepareDevDir(platform);

  const firstRun = !existsSync(join(devDir, "node_modules"));
  materialize(platform, devDir);
  if (firstRun) firstTimeSetup(devDir);

  const devServer = startDevServer(devDir);
  const watchers = watchAuthoringSource(platform, devDir);
  wireShutdown(watchers, devServer);
}

main();
