// The docs site is themed with pantoken's own output: the full @property token sheet from
// @pantoken/css, then the @pantoken/vitepress bridge that maps VitePress's --vp-* variables onto
// var(--instui-*). The site you're reading is a live demo of the VitePress renderer.
import type { Theme } from "vitepress";
import DefaultTheme from "vitepress/theme";
// The multi-theme token sheet (rebrand default + canvas/canvasHighContrast under
// `:root[data-pantoken-theme]`), generated by `scripts/site-themes.ts`. The palette selector in the
// nav toggles the attribute to re-theme the whole site. Replaces the single-theme @pantoken/css sheet.
import "./generated/site-themes.css";
import "@pantoken/vitepress/custom.css";
import "@pantoken/vitepress/components.css";
// The docs-only multi-theme component sheet: the rebrand rules unscoped (byte-for-byte the shipped
// `@pantoken/components/components.css`) plus the canvas/canvasHighContrast rules scoped under
// `:root[data-pantoken-theme="…"]`, generated by `scripts/components-sheet.ts`. The shipped sheet is
// lowered to one theme, so its `@media (--theme-*)` overrides are pruned; this restores them so the
// inline CSS-API `@example` previews re-theme on the attribute toggle. Mirrors site-themes.css above.
import "./generated/components.css";
// Import the utility + icon sheets from `formats/components/generated/` (source-derived, regenerated by
// the orchestrator cascade and bridged into HMR via `outputWatchPaths`) rather than
// `@pantoken/components/*` (which resolves to `dist`, only rebuilt by the nested-forbidden `vp pack`).
// This keeps utility/icon edits live during docs:dev. Fonts stay on the shipped sheet — stable
// @font-face rules whose url()s resolve against the packaged assets/fonts.
import "../../../formats/components/generated/utilities.css";
import "../../../formats/components/generated/icons.css";
import "../../../plugins/pantoken/custom-components/generated/custom-components.css";
import "../../../plugins/pantoken/custom-icons/generated/custom-icons.css";
import "@pantoken/components/fonts.css";
import VitePressMermaid from "../plugins/vitepress-mermaid/index.vue";
import CdnPicker from "./components/CdnPicker.vue";
import CdnPickerPage from "./components/CdnPickerPage.vue";
import GetStartedTabs from "./components/GetStartedTabs.vue";
// Import register() from the web-components SOURCE, not `@pantoken/web-components` (dist). The dist
// bundle is only rebuilt by `vp pack`, which can't run nested under vitepress — so a package import
// would freeze element behaviour + shadow CSS at the last pack. The source graph is Node-free (no
// node:/postcss/@cssdoc value imports) and needs no codegen: elements get CSS via Vite `?inline` and
// `@pantoken/components` *Css() functions, so Vite hot-reloads element `.ts` + co-located `.css` edits
// directly. register() is idempotent (it skips already-defined tags), so the barrel's own load-time
// register() plus the enhanceApp call below are safe.
// Extensionless (this file is type-checked; an explicit `.ts` needs allowImportingTsExtensions). Vite
// resolves it to src/index.ts at build/dev time.
import { register as registerWebComponents } from "../../../renderers/web-components/src/index";
import "@pantoken/demo/demo.css";
// `.instui-card` — the shared surface for the in-page CSS-API `@example` previews (`.css-example`) and
// the self-hosted demos. A static asset (not generated); the runner iframe loads the same file via ?css=.
import "@pantoken/demo/card.css";
import "./pantoken.css";
import Layout from "./Layout.vue";
import { applyTheme, getStoredTheme } from "./theme";

/** Reply to a booting runner with the stored theme, targeting the frame's own origin. */
function replyWithTheme(event: MessageEvent): void {
  // "*" only for an opaque sandboxed frame, which can't match a specific target origin.
  (event.source as Window | null)?.postMessage(
    { type: "pantoken-demo-theme", theme: getStoredTheme() },
    event.origin === "null" ? "*" : event.origin,
  );
}

/** Set the iframe (matched by its source window) to the height its runner reported. */
function applyRunnerSize(event: MessageEvent, height: number): void {
  const frame = [...document.querySelectorAll<HTMLIFrameElement>(".pantoken-demo__frame")].find(
    (f) => f.contentWindow === event.source,
  );
  if (!frame) return;
  // The reported height is the iframe's own content; `.css-example` (unlike the borderless `/play`
  // frame) carries a border, which under border-box sizing would otherwise eat into that content and
  // clip it — pad the assigned height back out by the border's width.
  const border = frame.classList.contains("css-example") ? 2 : 0;
  frame.style.height = `${height + border}px`;
}

/** View a demo/example's iframe fullscreen when its hoverable corner button is clicked. */
function requestDemoFullscreen(event: MouseEvent): void {
  const button = (event.target as Element | null)?.closest(".pantoken-demo__fullscreen");
  const frame = button?.closest(".pantoken-demo, .css-example-frame")?.querySelector("iframe");
  void frame?.requestFullscreen?.();
}

/** Demo message payloads accepted from runner iframes. */
type DemoMessage =
  | { type: "pantoken-demo-request-theme" }
  | { type: "pantoken-demo-size"; height: number };

/** Accept same-origin posts plus opaque sandboxed (`null`) runner posts. */
function isTrustedDemoOrigin(origin: string): boolean {
  return origin === window.location.origin || origin === "null";
}

/** Coerce unknown data into a loose payload object when possible. */
function asDemoPayload(data: unknown): { type?: string; height?: unknown } | null {
  if (!data || typeof data !== "object") return null;
  return data as { type?: string; height?: unknown };
}

/** Parse a validated demo-size message payload. */
function asSizeMessage(payload: { type?: string; height?: unknown }): DemoMessage | null {
  if (payload.type !== "pantoken-demo-size" || typeof payload.height !== "number") return null;
  return { type: payload.type, height: payload.height };
}

/** Narrow unknown postMessage payloads to known runner message variants. */
function asDemoMessage(data: unknown): DemoMessage | null {
  const payload = asDemoPayload(data);
  if (!payload) return null;
  if (payload.type === "pantoken-demo-request-theme") return { type: payload.type };
  return asSizeMessage(payload);
}

/** Dispatch one validated runner message. */
function handleDemoMessage(event: MessageEvent, message: DemoMessage): void {
  if (message.type === "pantoken-demo-request-theme") {
    replyWithTheme(event);
    return;
  }
  applyRunnerSize(event, message.height);
}

/**
 * Relay theme/size messages between the page and its demo runners. Only same-origin (or opaque
 * "null"-origin sandboxed) posts are accepted, so another page can't spoof size/theme messages.
 */
function relayDemoMessage(event: MessageEvent): void {
  if (!isTrustedDemoOrigin(event.origin)) return;
  const message = asDemoMessage(event.data);
  if (!message) return;
  handleDemoMessage(event, message);
}

export default {
  extends: DefaultTheme,
  Layout,
  enhanceApp(ctx) {
    DefaultTheme.enhanceApp?.(ctx);
    ctx.app.component("vitepress-mermaid", VitePressMermaid);
    // The interactive CDN combine-URL builder used on the CDN guide page (docs/guide/cdn.md).
    ctx.app.component("CdnPicker", CdnPicker);
    ctx.app.component("CdnPickerPage", CdnPickerPage);
    ctx.app.component("GetStartedTabs", GetStartedTabs);

    // Register the pantoken custom elements so the `@example` blocks on the web-components API pages
    // render live (the elements inline their own CSS; the token sheet above colours them). A no-op
    // during SSR — it early-returns without a DOM.
    registerWebComponents();

    // Wire the demo iframes: apply the persisted theme on load, then relay theme + size messages.
    if (typeof document !== "undefined") {
      // The head script already set the theme attribute (no flash); this reconciles the light/dark
      // class and broadcasts the theme to any demos already on the page.
      applyTheme(getStoredTheme());

      // The runner (inside each figure's iframe) posts the height it wants — its toolbar plus the body
      // (which hugs the demo by default, capped at 30rem, or whatever height the reader dragged it to).
      // Match the message to its frame by source window and set the height so the iframe mirrors it.
      window.addEventListener("message", relayDemoMessage);

      // The hoverable corner button on every demo/example frame — delegated so it covers frames added
      // after mount (e.g. inside an SSR-hydrated content area).
      document.addEventListener("click", requestDemoFullscreen);
    }
  },
} satisfies Theme;
