// The docs site is themed with pantoken's own output: the full @property token sheet from
// @pantoken/css, then the @pantoken/vitepress bridge that maps VitePress's --vp-* variables onto
// var(--instui-*). The site you're reading is a live demo of the VitePress renderer.
import type { Theme } from "vitepress";
import DefaultTheme from "vitepress/theme";
// The multi-theme token sheet (rebrand default + canvas/canvasHighContrast under
// `:root[data-pantoken-theme]`), generated by `scripts/site-themes.ts`. The palette selector in the
// nav toggles the attribute to re-theme the whole site. Replaces the single-theme @pantoken/css sheet.
import "./generated/site-themes.css";
import "@pantoken/vitepress/custom.css";
import "@pantoken/vitepress/components.css";
// The docs-only multi-theme component sheet: the rebrand rules unscoped (byte-for-byte the shipped
// `@pantoken/components/components.css`) plus the canvas/canvasHighContrast rules scoped under
// `:root[data-pantoken-theme="…"]`, generated by `scripts/components-sheet.ts`. The shipped sheet is
// lowered to one theme, so its `@media (--theme-*)` overrides are pruned; this restores them so the
// inline CSS-API `@example` previews re-theme on the attribute toggle. Mirrors site-themes.css above.
import "./generated/components.css";
// Import the utility + icon sheets from `formats/components/generated/` (source-derived, regenerated by
// the orchestrator cascade and bridged into HMR via `outputWatchPaths`) rather than
// `@pantoken/components/*` (which resolves to `dist`, only rebuilt by the nested-forbidden `vp pack`).
// This keeps utility/icon edits live during docs:dev. Fonts stay on the shipped sheet — stable
// @font-face rules whose url()s resolve against the packaged assets/fonts.
import "../../../formats/components/generated/utilities.css";
import "../../../formats/components/generated/icons.css";
import "@pantoken/components/fonts.css";
import VitePressMermaid from "../plugins/vitepress-mermaid/index.vue";
import CdnPicker from "./components/CdnPicker.vue";
// Import register() from the web-components SOURCE, not `@pantoken/web-components` (dist). The dist
// bundle is only rebuilt by `vp pack`, which can't run nested under vitepress — so a package import
// would freeze element behaviour + shadow CSS at the last pack. The source graph is Node-free (no
// node:/postcss/@cssdoc value imports) and needs no codegen: elements get CSS via Vite `?inline` and
// `@pantoken/components` *Css() functions, so Vite hot-reloads element `.ts` + co-located `.css` edits
// directly. register() is idempotent (it skips already-defined tags), so the barrel's own load-time
// register() plus the enhanceApp call below are safe.
// Extensionless (this file is type-checked; an explicit `.ts` needs allowImportingTsExtensions). Vite
// resolves it to src/index.ts at build/dev time.
import { register as registerWebComponents } from "../../../renderers/web-components/src/index";
import "@pantoken/demo/demo.css";
// `.instui-card` — the shared surface for the in-page CSS-API `@example` previews (`.css-example`) and
// the self-hosted demos. A static asset (not generated); the runner iframe loads the same file via ?css=.
import "@pantoken/demo/card.css";
import "./pantoken.css";
import Layout from "./Layout.vue";
import { applyTheme, getStoredTheme } from "./theme";

export default {
  extends: DefaultTheme,
  Layout,
  enhanceApp(ctx) {
    DefaultTheme.enhanceApp?.(ctx);
    ctx.app.component("vitepress-mermaid", VitePressMermaid);
    // The interactive CDN combine-URL builder used on the CDN guide page (docs/guide/cdn.md).
    ctx.app.component("CdnPicker", CdnPicker);

    // Register the pantoken custom elements so the `@example` blocks on the web-components API pages
    // render live (the elements inline their own CSS; the token sheet above colours them). A no-op
    // during SSR — it early-returns without a DOM.
    registerWebComponents();

    // Wire the demo iframes: apply the persisted theme on load, then relay theme + size messages.
    if (typeof document !== "undefined") {
      // The head script already set the theme attribute (no flash); this reconciles the light/dark
      // class and broadcasts the theme to any demos already on the page.
      applyTheme(getStoredTheme());

      // The runner (inside each figure's iframe) posts the height it wants — its toolbar plus the body
      // (which hugs the demo by default, capped at 30rem, or whatever height the reader dragged it to).
      // Match the message to its frame by source window and set the height so the iframe mirrors it.
      window.addEventListener("message", (event) => {
        const data = event.data as { type?: string; height?: number } | null;
        // A runner just booted and is asking which theme to render — reply to that frame only.
        if (data?.type === "pantoken-demo-request-theme") {
          (event.source as Window | null)?.postMessage(
            { type: "pantoken-demo-theme", theme: getStoredTheme() },
            "*",
          );
          return;
        }
        if (data?.type !== "pantoken-demo-size" || typeof data.height !== "number") return;
        const frame = [
          ...document.querySelectorAll<HTMLIFrameElement>(".pantoken-demo__frame"),
        ].find((f) => f.contentWindow === event.source);
        if (frame) frame.style.height = `${data.height}px`;
      });
    }
  },
} satisfies Theme;
