/**
 * Generate component capability metadata from authoritative sources:
 *
 * - CSS component names + icon usage: formats/components (via cdn-manifest pattern)
 * - Web-component element list + icon elements + dependency graph: renderers/web-components/elements-meta
 * - Behavioral JS classification: hand-maintained set below
 *
 * Outputs:
 *   docs/.vitepress/theme/components/componentMetadata.ts  — picked up by ComponentsPicker
 *   docs/public/component-capabilities.json               — machine-readable for AI consumers
 *
 * Wired into docs:assets so it regenerates on every dev/build run.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { COMPONENTS as CSS_RECORDS } from "../../formats/components/src/components/index.ts";
import {
  ELEMENTS,
  ICON_ELEMENTS,
  NESTED_DEPS,
} from "../../renderers/web-components/src/lib/elements-meta.ts";

// ── Classification ───────────────────────────────────────────────────────────

// CSS components that also have genuine interactive JS behavior when used without web components:
// overlays (open/close/position), navigation, command routing, or mode toggle.
const BEHAVIOR_COMPONENTS = new Set([
  "button",
  "calendar",
  "context-view",
  "in-place-edit",
  "modal",
  "popover",
  "tooltip",
  "tray",
  "tree-browser",
]);

// ── Derive component sets ────────────────────────────────────────────────────

const cssNames = new Set(CSS_RECORDS.filter((c) => c.kind === "component").map((c) => c.name));
const cssIconNames = new Set(
  CSS_RECORDS.filter(
    (c) => c.kind === "component" && /var\(--instui-icon-/.test(c.css({ prefix: "instui" })),
  ).map((c) => c.name),
);
const webNames = new Set(ELEMENTS as readonly string[]);
const iconElementNames = new Set(ICON_ELEMENTS as readonly string[]);

// ── Build records ────────────────────────────────────────────────────────────

type ComponentType = "css-only" | "js-only" | "both";

interface ComponentRecord {
  name: string;
  type: ComponentType;
  needsIcons: boolean;
  dependencies: readonly string[];
}

const all: ComponentRecord[] = [];

for (const name of [...new Set([...cssNames, ...webNames])].sort()) {
  const hasCss = cssNames.has(name);
  const hasWeb = webNames.has(name);
  const deps = (NESTED_DEPS[name] ?? []) as string[];
  const needsIcons = cssIconNames.has(name) || iconElementNames.has(name);

  let type: ComponentType;
  if (hasCss && hasWeb) {
    type = BEHAVIOR_COMPONENTS.has(name) ? "both" : "css-only";
  } else if (hasWeb) {
    type = "js-only";
  } else {
    type = "css-only";
  }

  all.push({ name, type, needsIcons, dependencies: deps });
}

// ── Emit componentMetadata.ts ────────────────────────────────────────────────

const tsGroups: Record<ComponentType, ComponentRecord[]> = {
  both: all.filter((c) => c.type === "both"),
  "css-only": all.filter((c) => c.type === "css-only"),
  "js-only": all.filter((c) => c.type === "js-only"),
};

function renderRecord(c: ComponentRecord): string {
  const deps = JSON.stringify(c.dependencies);
  return `  { name: "${c.name}", type: "${c.type}", needsIcons: ${c.needsIcons}, dependencies: ${deps} },`;
}

const tsLines = [
  `/**`,
  ` * Auto-generated by docs/scripts/component-capabilities.ts — do not edit by hand.`,
  ` * Re-run via \`vp run docs:assets\` or \`node docs/scripts/component-capabilities.ts\`.`,
  ` */`,
  ``,
  `export type ComponentType = "css-only" | "js-only" | "both";`,
  ``,
  `export interface ComponentMetadata {`,
  `  name: string;`,
  `  type: ComponentType;`,
  `  needsIcons: boolean;`,
  `  dependencies: readonly string[];`,
  `}`,
  ``,
  `export const COMPONENTS: readonly ComponentMetadata[] = [`,
  `  // Both CSS + JS (overlays, navigation, command routing)`,
  ...tsGroups.both.map(renderRecord),
  ``,
  `  // CSS only`,
  ...tsGroups["css-only"].map(renderRecord),
  ``,
  `  // JS only (web-component elements without a CSS counterpart)`,
  ...tsGroups["js-only"].map(renderRecord),
  `];`,
  ``,
  `export function createComponentMap(): Map<string, ComponentMetadata> {`,
  `  return new Map(COMPONENTS.map((c) => [c.name, c]));`,
  `}`,
  ``,
  `export function getAllDependencies(name: string): Set<string> {`,
  `  const comp = COMPONENTS.find((c) => c.name === name);`,
  `  if (!comp) return new Set();`,
  `  const deps = new Set<string>();`,
  `  const queue = [...comp.dependencies];`,
  `  while (queue.length > 0) {`,
  `    const dep = queue.shift();`,
  `    if (!dep || deps.has(dep)) continue;`,
  `    deps.add(dep);`,
  `    const depComp = COMPONENTS.find((c) => c.name === dep);`,
  `    if (depComp) queue.push(...depComp.dependencies);`,
  `  }`,
  `  return deps;`,
  `}`,
  ``,
  `export function groupByType(): Record<ComponentType, ComponentMetadata[]> {`,
  `  return {`,
  `    "css-only": COMPONENTS.filter((c) => c.type === "css-only"),`,
  `    "js-only": COMPONENTS.filter((c) => c.type === "js-only"),`,
  `    both: COMPONENTS.filter((c) => c.type === "both"),`,
  `  };`,
  `}`,
  ``,
];

const tsOut = resolve(import.meta.dirname, "../.vitepress/theme/components/componentMetadata.ts");
mkdirSync(dirname(tsOut), { recursive: true });
writeFileSync(tsOut, tsLines.join("\n"));

// ── Emit component-capabilities.json ────────────────────────────────────────

const cdn = "https://cdn.jsdelivr.net";

const json = {
  description:
    "InstUI component capability map. Each entry names the component, its CSS CDN URL, and — for interactive components — its JavaScript CDN URL.",
  components: all.map((c) => {
    const entry: Record<string, unknown> = { name: c.name };
    if (c.type !== "js-only") entry.css = `${cdn}/npm/@pantoken/components/dist/${c.name}.css`;
    if (c.type !== "css-only")
      entry.js = `${cdn}/npm/@pantoken/interactions/dist/${c.name}.iife.js`;
    if (c.dependencies.length) entry.requires = c.dependencies;
    return entry;
  }),
};

const jsonOut = resolve(import.meta.dirname, "../public/component-capabilities.json");
mkdirSync(dirname(jsonOut), { recursive: true });
writeFileSync(jsonOut, `${JSON.stringify(json, null, 2)}\n`);

const counts = {
  both: tsGroups.both.length,
  css: tsGroups["css-only"].length,
  js: tsGroups["js-only"].length,
};
console.log(
  `✓ docs: wrote componentMetadata.ts and component-capabilities.json` +
    ` (${counts.both} both, ${counts.css} css-only, ${counts.js} js-only)`,
);
