/**
 * Stage the self-hosted demo assets into `public/` so the site can serve them:
 *
 * - the built `@pantoken/demo` runner app → `public/play/`
 * - the token + component stylesheets the runner injects → `public/demos-assets/`
 * - the committed demo snippets in `docs/demos/*.html` → `public/demos/`
 *
 * `public/` is a build artifact (gitignored), so this runs before `vitepress dev`/`build`.
 */
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const docsRoot = join(import.meta.dirname, "..");
const publicDir = join(docsRoot, "public");

// The runner bundle uses content-hashed filenames, so a plain copy into an existing `play/` leaves the
// previous build's chunks behind — they pile up across rebuilds. Clear it first so only the current
// build's files remain. (demos-assets/ and demos/ use stable names and overwrite cleanly, so they're
// left as-is.)
const play = join(publicDir, "play");
rmSync(play, { recursive: true, force: true });
mkdirSync(play, { recursive: true });
const demoPkgDir = dirname(require.resolve("@pantoken/demo/package.json"));
const runnerDist = join(demoPkgDir, "dist/runner");
if (existsSync(runnerDist)) {
  cpSync(runnerDist, play, { recursive: true });
} else {
  console.warn(
    "⚠ @pantoken/demo runner is not built (run `vp run @pantoken/demo#build`); demos won't render.",
  );
}

const assets = join(publicDir, "demos-assets");
mkdirSync(assets, { recursive: true });

// The component + prose sheets are theme-independent (they only reference --instui-* tokens). Prose
// styles bare demo markup (headings, paragraphs, tables) with the InstUI look; it's scoped to
// .pantoken-prose, so it stays inert until the runner tags the result body with that class.
copyFileSync(
  require.resolve("@pantoken/components/components.css"),
  join(assets, "components.css"),
);
copyFileSync(require.resolve("@pantoken/components/prose.css"), join(assets, "prose.css"));
// The opt-in base/reset: the runner's result iframe is a pantoken-owned page, so it loads base too
// (page surface, box-sizing, base text) — this is also what the `base` demo showcases.
copyFileSync(require.resolve("@pantoken/components/base.css"), join(assets, "base.css"));
// The icon glyph classes (.instui-icon-<name>), so demos can render InstUI glyphs with no inline SVG.
copyFileSync(require.resolve("@pantoken/components/icons.css"), join(assets, "icons.css"));
// The experimental customizable-select enhancement (@supports base-select) — inert unless the browser
// supports it, so it's safe to always load; lets the simple-select demo show the styled dropdown.
copyFileSync(require.resolve("@pantoken/components/select.css"), join(assets, "select.css"));
// The cross-cutting utilities (spacing/colour classes + the View primitive), opt-in like the rest.
copyFileSync(require.resolve("@pantoken/components/utilities.css"), join(assets, "utilities.css"));

// The site's multi-theme token sheet (rebrand default + canvas/canvasHighContrast scoped to
// `:root[data-pantoken-theme]`), generated by scripts/site-themes.ts. The runner loads this same sheet
// and switches theme by toggling the attribute — no per-theme sheets. site-themes.ts runs before this
// script (see the `docs:assets` order), so the file is fresh.
copyFileSync(
  join(docsRoot, ".vitepress/theme/generated/site-themes.css"),
  join(assets, "site-themes.css"),
);

// `.instui-card` — the surface the /demos and the CSS-API live examples share. A static asset
// (tools/demo/assets/card.css); the host page imports it directly, and the runner loads the same file.
copyFileSync(require.resolve("@pantoken/demo/card.css"), join(assets, "card.css"));

// The focus-outline ring and the transition/stacking/visual-debug classes are theme-independent CSS,
// generated once from their plugin packages (site-themes.css and @pantoken/css are built without the
// plugins). Both the runner (via ?css=) and the main docs site (via <head> links) load these. The named
// elevation shadows are NOT plugins — they ship in @pantoken/components (base.css / components.css).
const { toCss } = require("@pantoken/css") as typeof import("@pantoken/css");
const { focusOutlineCss } =
  require("@pantoken/components") as typeof import("@pantoken/components");
const { transition } =
  require("@pantoken/plugin-transition") as typeof import("@pantoken/plugin-transition");
const { stacking } =
  require("@pantoken/plugin-stacking") as typeof import("@pantoken/plugin-stacking");
const { visualDebug } =
  require("@pantoken/plugin-visual-debug") as typeof import("@pantoken/plugin-visual-debug");
writeFileSync(join(assets, "focus-outline.css"), focusOutlineCss());
writeFileSync(join(assets, "transition.css"), toCss([], { plugins: [transition()] }));
writeFileSync(join(assets, "stacking.css"), toCss([], { plugins: [stacking()] }));
writeFileSync(join(assets, "visual-debug.css"), toCss([], { plugins: [visualDebug()] }));

const demosSrc = join(docsRoot, "demos");
const demosOut = join(publicDir, "demos");
mkdirSync(demosOut, { recursive: true });
let count = 0;
if (existsSync(demosSrc)) {
  for (const file of readdirSync(demosSrc)) {
    if (!file.endsWith(".html")) continue;
    copyFileSync(join(demosSrc, file), join(demosOut, file));
    count += 1;
  }
}

console.log(
  `✓ staged demo runner, the shared token + plugin sheets, and ${count} demo(s) to public/`,
);
