/**
 * Stage the self-hosted demo assets into `public/` so the site can serve them:
 *
 * - the built `@pantoken/demo` runner app → `public/play/`
 * - the token + component stylesheets the runner injects → `public/demos-assets/`
 * - the committed demo snippets in `docs/demos/*.html` → `public/demos/`
 *
 * `public/` is a build artifact (gitignored), so this runs before `vitepress dev`/`build`.
 */
import { copyFileSync, cpSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { writeComponentsSheet } from "./components-sheet.ts";
import { stageComponentAssets } from "./stage-component-assets.ts";
import { stagePluginAssets } from "./stage-plugin-assets.ts";
import { stageDemoSnippets } from "./stage-demo-snippets.ts";

const require = createRequire(import.meta.url);
const docsRoot = join(import.meta.dirname, "..");
const publicDir = join(docsRoot, "public");

// The runner bundle uses content-hashed filenames, so a plain copy into an existing `play/` leaves the
// previous build's chunks behind — they pile up across rebuilds. Clear it first so only the current
// build's files remain. (demos-assets/ and demos/ use stable names and overwrite cleanly, so they're
// left as-is.)
const play = join(publicDir, "play");
rmSync(play, { recursive: true, force: true });
mkdirSync(play, { recursive: true });
const demoPkgDir = dirname(require.resolve("@pantoken/demo/package.json"));
const runnerDist = join(demoPkgDir, "dist/runner");
if (existsSync(runnerDist)) {
  cpSync(runnerDist, play, { recursive: true });
} else {
  console.warn(
    "⚠ @pantoken/demo runner is not built (run `vp run @pantoken/demo#build`); demos won't render.",
  );
}

const assets = join(publicDir, "demos-assets");
mkdirSync(assets, { recursive: true });

// The shipped components.css is lowered to ONE theme (rebrand), so its `@media (--theme-*)` overrides
// are pruned — the reader's runtime theme switch (which toggles `data-pantoken-theme`) could never
// bring them back. Emit a docs-only multi-theme sheet instead: rebrand rules unscoped, plus the
// canvas/canvasHighContrast overrides scoped under `:root[data-pantoken-theme="…"]` so the attribute
// toggle activates them. `writeComponentsSheet` writes both the theme import
// (theme/generated/components.css, for the MAIN document's inline `@example` previews) and this
// demos-assets copy (for the /play iframes), so both surfaces respond to the switch. See
// components-sheet.ts / lib/scope-components.ts.
writeComponentsSheet();
// The single-theme component sheets the runner injects (prose, base, icons, select, utilities) plus the
// focus-outline ring — staged from `formats/components/generated/` (and source `focusOutlineCss`), NOT
// `@pantoken/components/*` (dist), so component edits stay live during docs:dev. See
// stage-component-assets.ts.
stageComponentAssets();

// The site's multi-theme token sheet (rebrand default + canvas/canvasHighContrast scoped to
// `:root[data-pantoken-theme]`), generated by scripts/site-themes.ts. The runner loads this same sheet
// and switches theme by toggling the attribute — no per-theme sheets. site-themes.ts runs before this
// script (see the `docs:assets` order), so the file is fresh.
copyFileSync(
  join(docsRoot, ".vitepress/theme/generated/site-themes.css"),
  join(assets, "site-themes.css"),
);

// `.instui-card` — the surface the /demos and the CSS-API live examples share. A static asset
// (tools/demo/assets/card.css); the host page imports it directly, and the runner loads the same file.
copyFileSync(require.resolve("@pantoken/demo/card.css"), join(assets, "card.css"));

// The transition/stacking/visual-debug decoration sheets, copied from each plugin's SOURCE-derived
// `generated/<name>.css` (NOT the plugin `dist` function) so they stay live during docs:dev — the
// orchestrator re-runs this on a plugin edit. Both the runner (via ?css=) and the main site (via <head>
// links) load them. focus-outline is staged with the component sheets above. See stage-plugin-assets.ts.
stagePluginAssets();

// The committed demo snippets (docs/demos/*.html) → public/demos/. See stage-demo-snippets.ts.
const count = stageDemoSnippets();

console.log(
  `✓ staged demo runner, the shared token + plugin sheets, and ${String(count)} demo(s) to public/`,
);
