/**
 * Inline the ported Pendo component CSS (`src/themes/instui/*.css`) into a generated TS module, so
 * the package ships the styles as string constants (the rolldown-based `vp pack` can't resolve
 * `?raw` imports). Source: `@instructure/pendo-global-css` (MIT). Runs before `vp pack`/`vp test`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const dir = join(root, "src/themes/instui");
const read = (name: string): string => readFileSync(join(dir, `${name}.css`), "utf8");

// key → camelCase export name (must match the imports in layers.ts).
const files = [
  "alert",
  "button",
  "card",
  "close-button",
  "img",
  "manual",
  "mask",
  "pagination",
  "popover",
  "radio-group",
  "select",
  "text",
  "textarea",
  "video",
  "view",
];

const toName = (f: string): string =>
  `${f.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())}Css`;

const lines = [
  "// GENERATED by scripts/embed.ts — do not edit by hand.",
  "// Source: @instructure/pendo-global-css (src/themes/instui, MIT).",
  "",
  ...files.map((f) => `export const ${toName(f)} = ${JSON.stringify(read(f))};`),
  "",
];

const outFile = join(root, "generated/embedded.ts");
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join("\n"));
console.log(`✓ embedded ${files.length} Pendo component CSS files`);
