/**
 * Inline the agent asset files into a generated TS module (so the package ships them as string
 * constants — markdown with code fences can't live in a TS template literal).
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const read = (path: string): string => readFileSync(join(root, path), "utf8");

// cursor.mdc holds only frontmatter; its body is interpolated from copilot-instructions.md so the
// two rule files can't drift out of sync.
const copilot = read("assets/copilot-instructions.md");

const assets: Record<string, string> = {
  agents: read("assets/AGENTS.md"),
  llms: read("assets/llms.txt"),
  cursor: `${read("assets/cursor.mdc").trimEnd()}\n\n${copilot}`,
  copilot,
  windsurf: read("assets/windsurf.md"),
  initSkill: read("skills/init-pantoken/SKILL.md"),
  scaffoldSkill: read("skills/scaffold-pantoken/SKILL.md"),
};

const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "assets.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const ASSETS: Record<string, string> = ${JSON.stringify(assets, null, 2)};\n`,
);
console.log(`✓ inlined ${Object.keys(assets).length} agent assets`);

// Generate locale bundles from i18n-cache
import { readdirSync } from "node:fs";
const i18nCacheDir = join(root, "i18n-cache");
const localesDir = join(outDir, "locales");
mkdirSync(localesDir, { recursive: true });

const localeMap: Record<string, string> = {};
try {
  const cacheFiles = readdirSync(i18nCacheDir);
  for (const file of cacheFiles) {
    if (!file.endsWith(".json")) continue;
    const locale = file.slice(0, -".json".length);
    const cachePath = join(i18nCacheDir, file);
    const bundle = JSON.parse(readFileSync(cachePath, "utf8"));

    // Generate a TypeScript file for this locale
    const tsContent = `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const LOCALE_${locale.toUpperCase()} = ${JSON.stringify(
      bundle,
      null,
      2,
    )} as const;\n`;
    writeFileSync(join(localesDir, `${locale}.ts`), tsContent);
    localeMap[locale] = `LOCALE_${locale.toUpperCase()}`;
  }
} catch {
  // i18n-cache directory doesn't exist yet, that's okay
}

// Generate the index that exports all locales
const indexContent = `// GENERATED by scripts/generate.ts — do not edit by hand.
${Object.entries(localeMap)
  .map(([locale, varName]) => `import { ${varName} } from "./${locale}.js";`)
  .join("\n")}

export const LOCALES: Record<string, Record<string, string>> = {
${Object.entries(localeMap)
  .map(([locale, varName]) => `  ${locale}: ${varName},`)
  .join("\n")}
};
`;
writeFileSync(join(localesDir, "index.ts"), indexContent);
if (Object.keys(localeMap).length > 0) {
  console.log(`✓ generated locale bundles for: ${Object.keys(localeMap).join(", ")}`);
}
