/**
 * Inline the agent asset files into a generated TS module (so the package ships them as string
 * constants — markdown with code fences can't live in a TS template literal).
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const read = (path: string): string => readFileSync(join(root, path), "utf8");

// cursor.mdc holds only frontmatter; its body is interpolated from copilot-instructions.md so the
// two rule files can't drift out of sync.
const copilot = read("assets/copilot-instructions.md");

const assets: Record<string, string> = {
  agents: read("assets/AGENTS.md"),
  llms: read("assets/llms.txt"),
  cursor: `${read("assets/cursor.mdc").trimEnd()}\n\n${copilot}`,
  copilot,
  windsurf: read("assets/windsurf.md"),
  initSkill: read("skills/init-pantoken/SKILL.md"),
  scaffoldSkill: read("skills/scaffold-pantoken/SKILL.md"),
};

const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "assets.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const ASSETS: Record<string, string> = ${JSON.stringify(assets, null, 2)};\n`,
);
console.log(`✓ inlined ${Object.keys(assets).length} agent assets`);
