/**
 * The low-level CSS builder: typed `@property` registrations followed by scoped declaration
 * sections. Ported from `@instructure/instui-generate-css-tokens`'s `utils.ts`.
 *
 * @module
 */
import type { PropertyRule } from "@pantoken/model";

/** One scoped block of custom properties, optionally wrapped in an `@layer`. */
export interface CssSection {
  /** Plain layer name (e.g. `"pantoken"`), no `@` prefix. Omit to skip the wrapper. */
  layer?: string;
  pairs: [string, string][];
}

function renderSection(scope: string, { layer, pairs }: CssSection): string {
  const declarations = [
    `  ${scope} {`,
    ...pairs.map(([name, val]) => `    ${name}: ${val.trim()};`),
    "  }",
  ];
  return layer ? [`@layer ${layer} {`, ...declarations, "}"].join("\n") : declarations.join("\n");
}

function renderProperty({ name, syntax, value }: PropertyRule, inherits: boolean): string {
  return [
    `@property ${name} {`,
    `  syntax: "${syntax}";`,
    `  inherits: ${inherits};`,
    `  initial-value: ${value.trim()};`,
    `}`,
  ].join("\n");
}

/**
 * Build a CSS file string: typed `@property` registrations (top-level, theme-agnostic) followed by
 * one or more scoped declaration sections (whose selector the consuming build may rewrite).
 *
 * @example Register one typed property and emit a scoped declaration
 * ```ts
 * import { buildCssFile } from "@pantoken/css";
 *
 * buildCssFile({
 *   comments: ["/* my tokens *\/"],
 *   scope: ":root",
 *   properties: [{ name: "--instui-color-brand", syntax: "<color>", value: "#0374b5" }],
 *   sections: [{ pairs: [["--instui-color-text-base", "var(--instui-color-brand)"]] }],
 * });
 * ```
 *
 * @example Wrap a section in a CSS cascade layer
 * ```ts
 * import { buildCssFile } from "@pantoken/css";
 *
 * buildCssFile({
 *   comments: [],
 *   scope: ":root",
 *   sections: [{ layer: "pantoken", pairs: [["--instui-spacing-space-md", "1rem"]] }],
 * });
 * ```
 */
export function buildCssFile({
  comments,
  scope,
  properties = [],
  sections,
  inherits = true,
}: {
  comments: string[];
  scope: string;
  properties?: PropertyRule[];
  sections: CssSection[];
  inherits?: boolean;
}): string {
  const propertyBlock = properties.map((p) => renderProperty(p, inherits)).join("\n\n");
  const sectionBlocks = sections
    .filter((s) => s.pairs.length > 0)
    .map((s) => renderSection(scope, s));
  const blocks = [propertyBlock, ...sectionBlocks].filter(Boolean);
  return [
    `/* DO NOT EDIT — generated by @pantoken/css */`,
    "",
    ...comments,
    "",
    ...blocks,
    "",
  ].join("\n");
}
