/**
 * `@pantoken/cli` — `pantoken generate <target>`.
 *
 * Emits native and other non-npm design-token source into a consumer repo — the targets that don't
 * fit the npm-package model. Supported now: `swift` (with an SPM `Package.swift` manifest stub, so
 * registry publishing is later a config flip), `android`, `compose`, `flutter`, `wordpress`,
 * `vanilla`, `drupal`, `swatches`, `rust`, `icon-font`, `pendo`, `jekyll`, `hugo`, and `mintlify`.
 *
 * @module
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { generateAndroid } from "@pantoken/android";
import { generateCompose } from "@pantoken/compose";
import { generateFlutter } from "@pantoken/flutter";
import { buildIconFont } from "@pantoken/icon-font";
import { buildPendoCss } from "@pantoken/pendo";
import { toDrupalTheme } from "@pantoken/drupal";
import { toHugoAssets } from "@pantoken/hugo";
import { toJekyllAssets } from "@pantoken/jekyll";
import { toMintlifyConfig } from "@pantoken/mintlify";
import { generateRust } from "@pantoken/rust";
import { toAse, toGpl, toSketchPalette, toSvg, toSwatches } from "@pantoken/swatches";
import { generateSwift } from "@pantoken/swift";
import { byTheme } from "@pantoken/tokens";
import { toVanillaVariables } from "@pantoken/vanilla";
import { toThemeJson } from "@pantoken/wordpress";
import type { Theme } from "@pantoken/model";

/** The parsed CLI invocation. */
export interface CliArgs {
  command: string;
  target: string;
  out: string;
  theme: Theme;
  className: string;
  /** Icon names to emit as native assets (from `--icons a,b,c`). */
  icons?: string[];
  /** Output format, for targets that support several (e.g. `swatches --format ase`). */
  format?: string;
  /** Pendo: skip `@scope` wrapping (`--no-scope`). */
  noScope?: boolean;
  /** Pendo: skip `!important` (`--no-important`). */
  noImportant?: boolean;
  /** Pendo: skip token pruning (`--no-prune`). */
  noPrune?: boolean;
}

const SUPPORTED = new Set([
  "swift",
  "android",
  "compose",
  "flutter",
  "wordpress",
  "vanilla",
  "drupal",
  "swatches",
  "rust",
  "icon-font",
  "pendo",
  "jekyll",
  "hugo",
  "mintlify",
]);
const PLANNED = new Set<string>();

/**
 * Parse `generate <target> [--out dir] [--theme t] [--class Name]`.
 *
 * @example Positional target plus value flags
 * ```ts
 * import { parseArgs } from "@pantoken/cli";
 *
 * parseArgs(["generate", "swift", "--out", "./ios", "--theme", "canvas"]);
 * // → { command: "generate", target: "swift", out: "./ios", theme: "canvas",
 * //     className: "PanTokens", … }
 * ```
 *
 * @example Boolean flags and a comma-separated --icons list
 * ```ts
 * import { parseArgs } from "@pantoken/cli";
 *
 * const args = parseArgs(["generate", "pendo", "--no-scope", "--icons", "arrow-left,check-mark"]);
 * args.noScope; // → true
 * args.icons;   // → ["arrow-left", "check-mark"]
 * ```
 */
export function parseArgs(argv: readonly string[]): CliArgs {
  const positionals: string[] = [];
  const flags: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith("--")) {
      // A flag with no following value (end of args or another flag next) is a boolean.
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) flags[arg.slice(2)] = "true";
      else flags[arg.slice(2)] = argv[++i];
    } else {
      positionals.push(arg);
    }
  }
  return {
    command: positionals[0] ?? "",
    target: positionals[1] ?? "",
    out: flags.out ?? "./pantoken-out",
    theme: (flags.theme as Theme) ?? "rebrand",
    className: flags.class ?? "PanTokens",
    icons: flags.icons ? flags.icons.split(",").filter(Boolean) : undefined,
    format: flags.format,
    noScope: "no-scope" in flags,
    noImportant: "no-important" in flags,
    noPrune: "no-prune" in flags,
  };
}

const SWIFT_PACKAGE_MANIFEST = (name: string) =>
  `// swift-tools-version:5.9
// Generated by @pantoken/cli — publish to SwiftPM by pushing this package.
import PackageDescription

let package = Package(
    name: "${name}",
    platforms: [.iOS(.v15), .macOS(.v12)],
    products: [.library(name: "${name}", targets: ["${name}"])],
    targets: [.target(name: "${name}", path: "Sources/${name}")]
)
`;

/**
 * Run the CLI.
 *
 * @example Generate Swift tokens into a consumer repo
 * ```ts
 * import { run } from "@pantoken/cli";
 *
 * // Writes Sources/PanTokens/Tokens.swift + Package.swift under ./ios/DesignTokens.
 * await run(["generate", "swift", "--out", "./ios/DesignTokens"]);
 * ```
 *
 * @example Generate a themed swatch palette in a specific format
 * ```ts
 * import { run } from "@pantoken/cli";
 *
 * await run(["generate", "swatches", "--format", "gpl", "--theme", "canvas", "--out", "./out"]);
 * ```
 */
export async function run(argv: readonly string[]): Promise<void> {
  const args = parseArgs(argv);

  if (args.command !== "generate") {
    throw new Error(
      `Unknown command "${args.command}". Usage: pantoken generate <target> [--out dir] [--theme t]`,
    );
  }
  if (PLANNED.has(args.target)) {
    throw new Error(
      `Target "${args.target}" is planned but not implemented yet. Available now: ${[...SUPPORTED].join(", ")}.`,
    );
  }
  if (!SUPPORTED.has(args.target)) {
    throw new Error(`Unknown target "${args.target}". Available: ${[...SUPPORTED].join(", ")}.`);
  }

  if (args.target === "swift") {
    // Emit into Sources/<className> so the SPM manifest stub finds it.
    const sourcesDir = join(args.out, "Sources", args.className);
    const file = await generateSwift({
      outDir: sourcesDir,
      theme: args.theme,
      className: args.className,
      icons: args.icons,
    });
    const manifestPath = join(args.out, "Package.swift");
    mkdirSync(dirname(manifestPath), { recursive: true });
    writeFileSync(manifestPath, SWIFT_PACKAGE_MANIFEST(args.className));
    console.log(`✓ pantoken: wrote ${file}`);
    console.log(`✓ pantoken: wrote ${manifestPath} (SwiftPM manifest stub)`);
    return;
  }

  if (args.target === "android") {
    const files = await generateAndroid({ outDir: args.out, theme: args.theme, icons: args.icons });
    for (const file of files) console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "compose") {
    const file = await generateCompose({
      outDir: args.out,
      theme: args.theme,
      className: args.className,
    });
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "flutter") {
    const file = await generateFlutter({
      outDir: args.out,
      theme: args.theme,
      className: args.className,
      icons: args.icons,
    });
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "wordpress") {
    mkdirSync(args.out, { recursive: true });
    const file = join(args.out, "theme.json");
    writeFileSync(file, `${JSON.stringify(toThemeJson(byTheme(args.theme)), null, 2)}\n`);
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "vanilla") {
    mkdirSync(args.out, { recursive: true });
    const file = join(args.out, "variables.json");
    writeFileSync(file, `${JSON.stringify(toVanillaVariables(byTheme(args.theme)), null, 2)}\n`);
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "mintlify") {
    mkdirSync(args.out, { recursive: true });
    const file = join(args.out, "docs.json");
    writeFileSync(file, `${JSON.stringify(toMintlifyConfig(byTheme(args.theme)), null, 2)}\n`);
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "drupal") {
    for (const asset of toDrupalTheme()) {
      const file = join(args.out, asset.path);
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, asset.content);
      console.log(`✓ pantoken: wrote ${file}`);
    }
    return;
  }

  if (args.target === "rust") {
    const format = args.format === "iced" ? "iced" : "egui";
    const file = args.out.includes(".") ? args.out : join(args.out, "tokens.rs");
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, generateRust({ format, theme: args.theme }));
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "swatches") {
    const format = args.format ?? "ase";
    const swatches = toSwatches(byTheme(args.theme));
    const ext = format === "sketch" ? "sketchpalette" : format;
    const file = args.out.includes(".") ? args.out : join(args.out, `instructure.${ext}`);
    mkdirSync(dirname(file), { recursive: true });
    if (format === "ase") writeFileSync(file, toAse(swatches));
    else if (format === "gpl") writeFileSync(file, toGpl(swatches));
    else if (format === "sketch")
      writeFileSync(file, `${JSON.stringify(toSketchPalette(swatches), null, 2)}\n`);
    else if (format === "svg") writeFileSync(file, toSvg(swatches));
    else throw new Error(`Unknown swatch format "${format}". Use ase, gpl, sketch, or svg.`);
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }

  if (args.target === "icon-font") {
    const font = await buildIconFont({
      theme: args.theme,
      icons: args.icons,
      fontName: args.className,
    });
    mkdirSync(args.out, { recursive: true });
    const ttf = join(args.out, `${args.className}.ttf`);
    const woff2 = join(args.out, `${args.className}.woff2`);
    const cssFile = join(args.out, "icons.css");
    const codepoints = join(args.out, "codepoints.json");
    writeFileSync(ttf, font.ttf);
    writeFileSync(woff2, font.woff2);
    writeFileSync(cssFile, font.css);
    writeFileSync(codepoints, `${JSON.stringify(font.codepoints, null, 2)}\n`);
    for (const file of [ttf, woff2, cssFile, codepoints]) {
      console.log(`✓ pantoken: wrote ${file}`);
    }
    return;
  }

  if (args.target === "jekyll" || args.target === "hugo") {
    const assets = args.target === "jekyll" ? toJekyllAssets() : toHugoAssets();
    for (const asset of assets) {
      const file = join(args.out, asset.path);
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, asset.content);
      console.log(`✓ pantoken: wrote ${file}`);
    }
    return;
  }

  if (args.target === "pendo") {
    mkdirSync(args.out, { recursive: true });
    const file = join(args.out, "global.css");
    writeFileSync(
      file,
      buildPendoCss({
        theme: args.theme,
        scope: !args.noScope,
        important: !args.noImportant,
        prune: !args.noPrune,
      }),
    );
    console.log(`✓ pantoken: wrote ${file}`);
    return;
  }
}
