/**
 * Emit the pantoken IR as Less variables. Values are resolved to concrete, single-mode values so
 * the output is a self-contained Less token file (`@instui-color-brand: #0374b5;`). Icon tokens are
 * skipped — they belong in CSS, not Less variables.
 *
 * @module
 */
import { resolveTokens } from "@pantoken/utils";
import type { Mode } from "@pantoken/utils";
import type { Token } from "@pantoken/model";

export type { Mode } from "@pantoken/utils";

/** Options for {@link toLess}. */
export interface ToLessOptions {
  /** Which colour mode to resolve (default `"light"`). */
  mode?: Mode;
}

/**
 * Emit Less variables for a token IR.
 *
 * @param tokens - The IR (e.g. from `@pantoken/tokens`).
 * @param options - {@link ToLessOptions}.
 * @returns The Less source string.
 *
 * @example Emit the default (light) variables
 * ```ts
 * import { toLess } from "@pantoken/less";
 * import { tokens } from "@pantoken/tokens";
 *
 * toLess(tokens); // "@instui-color-brand: #0374b5;\n…"
 * ```
 *
 * @example Resolve the dark mode of another theme
 * ```ts
 * import { toLess } from "@pantoken/less";
 * import { byTheme } from "@pantoken/tokens";
 *
 * toLess(byTheme("canvas"), { mode: "dark" });
 * ```
 */
export function toLess(tokens: readonly Token[], options: ToLessOptions = {}): string {
  const resolved = resolveTokens(tokens, { mode: options.mode ?? "light" });
  const lines = ["// DO NOT EDIT — generated by @pantoken/less", ""];
  for (const token of tokens) {
    if (token.meta?.kind === "icon") continue;
    lines.push(`@${token.name.replace(/^--/, "")}: ${resolved.get(token.name) ?? token.value};`);
  }
  return `${lines.join("\n")}\n`;
}
