import { readdirSync } from "node:fs";
import { join } from "node:path";
import { extendBase } from "../../vite.config.base.ts";

// Entries are the aggregator-generated files under src/ (index.ts + one per target).
const srcDir = join(import.meta.dirname, "src");
const entry = readdirSync(srcDir)
  .filter((f) => f.endsWith(".ts"))
  .map((f) => `src/${f}`);

export default extendBase({
  run: { tasks: { build: { command: ["vp run aggregate", "vp pack"] } } },
  pack: {
    entry: entry.length > 0 ? entry : ["src/index.ts"],
    // Exports are generated by @pantoken/aggregate.
    exports: false,
  },
});
