import { readdirSync } from "node:fs";
import { join } from "node:path";
import { defineConfig } from "vite-plus";

// Entries are the aggregator-generated files under src/ (index.ts + one per target).
const srcDir = join(import.meta.dirname, "src");
const entry = readdirSync(srcDir)
  .filter((f) => f.endsWith(".ts"))
  .map((f) => `src/${f}`);

export default defineConfig({
  run: {
    tasks: {
      build: {
        command: ["vp run aggregate", "vp pack"],
        // node_modules/.modules.yaml is rewritten by every CI reinstall; excluding it keeps
        // vp pack a cache hit across jobs instead of re-packing on every run.
        input: [{ auto: true }, { pattern: "!node_modules/.modules.yaml", base: "workspace" }],
      },
    },
  },
  pack: {
    entry: entry.length > 0 ? entry : ["src/index.ts"],
    dts: true,
    // Exports are generated by @pantoken/aggregate.
    exports: false,
  },
  lint: {
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  fmt: {},
});
