import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { I18nConfig } from "./config.ts";
import { resolveMessagesForLocale } from "./pipeline.ts";

/** Generate one locale module and a `MESSAGES` barrel from a messages-space's PO catalogs. */
export function generateMessageBundles(
  config: I18nConfig,
  configDir: string,
  spaceId: string,
  locales: readonly string[],
  outDir: string,
): void {
  const localesDir = join(outDir, "locales");
  mkdirSync(localesDir, { recursive: true });
  const localeMap: Array<{ locale: string; variable: string }> = [];
  for (const locale of locales) {
    const variable = `LOCALE_${locale.toUpperCase().replaceAll("-", "_")}`;
    const strings = resolveMessagesForLocale(config, configDir, spaceId, locale).strings;
    writeFileSync(
      join(localesDir, `${locale}.ts`),
      `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const ${variable} = ${JSON.stringify(strings, null, 2)} as const;\n`,
    );
    localeMap.push({ locale, variable });
  }
  writeFileSync(
    join(localesDir, "index.ts"),
    `// GENERATED by scripts/generate.ts — do not edit by hand.\n${localeMap
      .map(({ locale, variable }) => `import { ${variable} } from "./${locale}.js";`)
      .join("\n")}\n\nexport const MESSAGES: Record<string, Record<string, string>> = {\n${localeMap
      .map(({ locale, variable }) => `  ${JSON.stringify(locale)}: ${variable},`)
      .join("\n")}\n};\n`,
  );
}
