/**
 * Inlines `templates/cssdoc.jsonc` (real JSONC — not strict JSON, so it can't use a
 * `with { type: "json" }` import) into a generated string-constant module, so `blockCssdoc` ships
 * it without depending on `vp pack`'s (unsupported) `?raw` resolution. See
 * `docs/engineering-log.md`'s "`vp pack` doesn't resolve `?raw`" entry.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const cssdocJson = readFileSync(join(root, "templates/cssdoc.jsonc"), "utf8");

const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "cssdoc.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\nexport const CSSDOC_JSON: string = ${JSON.stringify(cssdocJson)};\n`,
);
console.log("✓ inlined templates/cssdoc.jsonc");
