/**
 * Builds `generated/theme.css`/`theme.js` (the jsDelivr-default, unpinned output of
 * {@link buildTheme}) — copied verbatim into `dist/` by `vp pack` for the static `./theme.css`/
 * `./theme.js` exports — and inlines them into a generated string-constant module, so this package
 * ships them without depending on `vp pack`'s (unsupported) `?raw` resolution. See
 * `docs/engineering-log.md`'s "`vp pack` doesn't resolve `?raw`" entry.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { buildTheme } from "../src/build-theme.ts";

const root = resolve(import.meta.dirname, "..");
const { css: themeCss, js: themeJs } = buildTheme({ provider: "jsdelivr" });

const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "theme.css"), themeCss);
writeFileSync(join(outDir, "theme.js"), themeJs);
writeFileSync(
  join(outDir, "theme.ts"),
  `// GENERATED by scripts/generate.ts — do not edit by hand.\n` +
    `export const THEME_CSS: string = ${JSON.stringify(themeCss)};\n` +
    `export const THEME_JS: string = ${JSON.stringify(themeJs)};\n`,
);
console.log("✓ built generated/theme.css and generated/theme.js, and inlined them");
