import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, test } from "vite-plus/test";
import { aggregate, discoverTargets } from "../src/index.ts";

function fixtureMeta(deps: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), "pantoken-meta-"));
  mkdirSync(join(dir, "src"));
  writeFileSync(
    join(dir, "package.json"),
    JSON.stringify({ name: "pantoken", dependencies: deps }),
  );
  return dir;
}

test("discoverTargets returns nothing when there are no deps", () => {
  expect(discoverTargets(fixtureMeta({}))).toEqual([]);
});

test("aggregate writes a barrel and resets the exports map", () => {
  const dir = fixtureMeta({});
  const targets = aggregate({ metaDir: dir });
  expect(targets).toEqual([]);
  const index = readFileSync(join(dir, "src", "index.ts"), "utf8");
  expect(index).toContain("GENERATED by @pantoken/aggregate");
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  expect(pkg.exports["."]).toBe("./dist/index.mjs");
  expect(pkg.exports["./package.json"]).toBe("./package.json");
});
